-- English localization file for enUS and enGB.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0");
local L 
if UnitName('player') ~= 'Elvz' and UnitName('player') ~= 'Gronckle' then
	L = AceLocale:NewLocale("ElvUI", "enUS", true, true);
else
	L = AceLocale:NewLocale("ElvUI", "enUS", true);
end

if not L then return; end

--ActionBars
L[" |cff00ff00bound to |r"] = " |cff00ff00bound to |r"
L["Action Paging"] = "Action Paging"
L["ActionBars"] = "ActionBars"
L["Anchor Point"] = "Anchor Point" --also in unitframes
L["Backdrop"] = "Backdrop"
L["Bar "] = "Bar "
L["Binding"] = "Binding"
L["Buttons Per Row"] = "Buttons Per Row"
L["Buttons"] = "Buttons"
L["Color when the text is about to expire"] = "Color when the text is about to expire"
L["Color when the text is in the days format."] = "Color when the text is in the days format."
L["Color when the text is in the hours format."] = "Color when the text is in the hours format."
L["Color when the text is in the minutes format."] = "Color when the text is in the minutes format."
L["Color when the text is in the seconds format."] = "Color when the text is in the seconds format."
L["Cooldown Text"] = "Cooldown Text"
L["Days"] = "Days"
L["Discard"] = "Discard"
L["Display bind names on action buttons."] = "Display bind names on action buttons."
L["Display cooldown text on anything with the cooldown spiril."] = "Display cooldown text on anything with the cooldown spiril."
L["Display macro names on action buttons."] = "Display macro names on action buttons."
L["Expiring"] = "Expiring"
L["Height Multiplier"] = "Height Multiplier"
L["Hours"] = "Hours"
L["Key"] = "Key"
L["Keybind Mode"] = "Keybind Mode"
L["Keybind Text"] = "Keybind Text"
L["KEY_ALT"] = "A"
L["KEY_BUTTON3"] = "M3"
L["KEY_CTRL"] = "C"
L["KEY_DELETE"] = "Del"
L["KEY_HOME"] = "Hm"
L["KEY_INSERT"] = "Ins"
L["KEY_MOUSEBUTTON"] = "M"
L["KEY_MOUSEWHEELDOWN"] = "MwD"
L["KEY_MOUSEWHEELUP"] = "MwU"
L["KEY_NUMPAD"] = "N"
L["KEY_PAGEDOWN"] = "PD"
L["KEY_PAGEUP"] = "PU"
L["KEY_SHIFT"] = "S"
L["KEY_SPACE"] = "SpB"
L["LOCK_AB_ERROR"] = "It has come to our attention that you do not have your actionbars locked. This may cause abilities to be used while dragging buttons to differant slots. Please run the Set CVar portion of the Installation process (Step 2). This can be done by typing /ec and clicking the Install button."
L["Low Threshold"] = "Low Threshold"
L["Macro Text"] = "Macro Text"
L['Max Paging'] = true;
L["Minutes"] = "Minutes"
L["Multiply the backdrops height or width by this value. This is usefull if you wish to have more than one bar behind a backdrop."] = "Multiply the backdrops height or width by this value. This is usefull if you wish to have more than one bar behind a backdrop."
L["No bindings set."] = "No bindings set."
L["Pet Bar"] = "Pet Bar"
L["Restore Bar"] = "Restore Bar"
L["Restore the actionbars default settings"] = "Restore the actionbars default settings"
L["Seconds"] = "Seconds"
L["Set the font size of the action buttons."] = "Set the font size of the action buttons."
L["ShapeShift Bar"] = "ShapeShift Bar"
L["The ammount of buttons to display per row."] = "The ammount of buttons to display per row."
L["The ammount of buttons to display."] = "The ammount of buttons to display."
L["The first button anchors itself to this point on the bar."] = "The first button anchors itself to this point on the bar."
L["The size of the action buttons."] = "The size of the action buttons."
L["Threshold before text turns red and is in decimal form. Set to -1 for it to never turn red"] = "Threshold before text turns red and is in decimal form. Set to -1 for it to never turn red"
L["Toggles the display of the actionbars backdrop."] = "Toggles the display of the actionbars backdrop."
L["Visibility State"] = "Visibility State"
L['When enabled the main actionbar will use the maximum amount of pages available. This means if you have another actionbar disabled, the actionbar page will become available on the main actionbar. Having this disabled will limit the main actionbar to two pages.'] = true;
L["Width Multiplier"] = "Width Multiplier"
L[ [=[This works like a macro, you can run different situations to get the actionbar to page differently.
 Example: '[combat] 2;']=] ] = [=[This works like a macro, you can run different situations to get the actionbar to page differently.
 Example: '[combat] 2;']=]
L[ [=[This works like a macro, you can run different situations to get the actionbar to show/hide differently.
 Example: '[combat] show;hide']=] ] = [=[This works like a macro, you can run different situations to get the actionbar to show/hide differently.
 Example: '[combat] show;hide']=]

--Bags
L["Ascending"] = "Ascending"
L["Bag Columns"] = "Bag Columns"
L["Bag-Bar"] = "Bag-Bar"
L["Bags"] = "Bags"
L["BAGS_DESC"] = "Adjust bag settings for ElvUI."
L["Bank Columns"] = "Bank Columns"
L["Bar Direction"] = "Bar Direction"
L["Bottom to Top"] = "Bottom to Top"
L["Button Size"] = "Button Size"
L["Button Spacing"] = "Button Spacing"
L["Click to search.."] = "Click to search.."
L["copperabbrev"] = "|cffeda55fc|r" --Also used in gold datatext
L["Delete Grays"] = "Delete Grays"
L["Deleted %d gray items. Total Worth: %s"] = "Deleted %d gray items. Total Worth: %s"
L["Descending"] = "Descending"
L["Direction the bag sorting will use to allocate the items."] = "Direction the bag sorting will use to allocate the items."
L["Enable Bag-Bar"] = "Enable Bag-Bar"
L["Enable/Disable the all-in-one bag."] = "Enable/Disable the all-in-one bag."
L["Enable/Disable the Bag-Bar."] = "Enable/Disable the Bag-Bar."
L["goldabbrev"] = "|cffffd700g|r" --Also used in gold datatext
L["Hold Shift:"] = "Hold Shift:"
L["Mouse Over"] = "Mouse Over"
L["No gray items to delete."] = "No gray items to delete."
L["No gray items to sell."] = "No gray items to sell."
L["Number of columns (width) of bags. Set it to 0 to match the width of the chat panels."] = "Number of columns (width) of bags. Set it to 0 to match the width of the chat panels."
L["Number of columns (width) of the bank. Set it to 0 to match the width of the chat panels."] = "Number of columns (width) of the bank. Set it to 0 to match the width of the chat panels."
L["Purchase"] = "Purchase"
L["Set the size of your bag buttons."] = "Set the size of your bag buttons."
L["silverabbrev"] = "|cffc7c7cfs|r" --Also used in gold datatext
L["Sort Bags"] = "Sort Bags"
L["Sort Direction"] = "Sort Direction"
L["Sort Orientation"] = "Sort Orientation"
L["Sort Special"] = "Sort Special"
L["Stack Items"] = "Stack Items"
L["Stack Special"] = "Stack Special"
L["The direction that the bag frames be (Horizontal or Vertical)."] = "The direction that the bag frames be (Horizontal or Vertical)."
L["The direction that the bag frames will grow from the anchor."] = "The direction that the bag frames will grow from the anchor."
L["The frame is not shown unless you mouse over the frame."] = "The frame is not shown unless you mouse over the frame."
L["The spacing between buttons."] = "The spacing between buttons."
L["Toggle Bags"] = "Toggle Bags"
L["Top to Bottom"] = "Top to Bottom"
L["Vendor Grays"] = "Vendor Grays"
L["Vendored gray items for:"] = "Vendored gray items for:"
L["X Offset"] = "X Offset"
L["Y Offset"] = "Y Offset"  --Another variation in unitframes yOffset
L["You must be at a vendor."] = "You must be at a vendor."

--Buffs and Debuffs
L['AURAS_DESC'] = 'Configure the aura icons that appear near the minimap.';
L['Begin a new row or column after this many auras.'] = true;
L['Consolidated Buffs'] = true;
L['Defines how the group is sorted.'] = true;
L['Defines the sort order of the selected sort method.'] = true;
L['Display the consolidated buffs bar.'] = true;
L['Index'] = true;
L['Indicate whether buffs you cast yourself should be separated before or after.'] = true;
L['Limit the number of rows or columns.'] = true;
L['Max Wraps'] = true;
L['Name'] = true;
L['No Sorting'] = true;
L["Other's First"] = true;
L['Seperate'] = true;
L['Set the size of the individual auras.'] = true;
L['Sort Direction'] = true;
L['Sort Method'] = true;
L['Time'] = true;
L['Wrap After'] = true;
L['X Spacing'] = true;
L['Y Spacing'] = true;
L['Your Auras First'] = true;

--Chat
L["Attempt to create URL links inside the chat."] = "Attempt to create URL links inside the chat."
L["BG"] = "BG"
L["BGL"] = "BGL"
L["BN:"] = "BN:"
L["Chat Bubbles"] = "Chat Bubbles"
L["Chat"] = "Chat"
L["CHAT_DESC"] = "Adjust chat settings for ElvUI."
L["Copy Text"] = "Copy Text"
L["Display the hyperlink tooltip while hovering over a hyperlink."] = "Display the hyperlink tooltip while hovering over a hyperlink."
L["DND"] = "DND"
L["Font Outline"] = "Font Outline" --Also used in UnitFrames section
L["Font"] = "Font"
L["G"] = "G"
L["Hyperlink Hover"] = "Hyperlink Hover"
L["Keyword Alert"] = true;
L['Keywords'] = true;
L['List of words to color in chat if found in a message. If you wish to add multiple words you must seperate the word with a comma. To search for your current name you can use %MYNAME%.\n\nExample:\n%MYNAME%, ElvUI, RBGs, Tank'] = true;
L["Number of time in seconds to scroll down to the bottom of the chat window if you are not scrolled down completely."] = "Number of time in seconds to scroll down to the bottom of the chat window if you are not scrolled down completely."
L["O"] = "O"
L["P"] = "P"
L["PG"] = "PG"
L["PL"] = "PL"
L["Prevent the same messages from displaying in chat more than once within this set amount of seconds, set to zero to disable."] = "Prevent the same messages from displaying in chat more than once within this set amount of seconds, set to zero to disable."
L["R"] = "R"
L["RL"] = "RL"
L["RW"] = "RW"
L['says'] = true;
L["Scroll Interval"] = "Scroll Interval"
L["Set the font outline."] = "Set the font outline." --Also used in UnitFrames section
L["Short Channels"] = "Short Channels"
L["Shorten the channel names in chat."] = "Shorten the channel names in chat."
L["Spam Interval"] = "Spam Interval"
L["Sticky Chat"] = "Sticky Chat"
L["URL Links"] = "URL Links"
L["When opening the Chat Editbox to type a message having this option set means it will retain the last channel you spoke in. If this option is turned off opening the Chat Editbox should always default to the SAY channel."] = "When opening the Chat Editbox to type a message having this option set means it will retain the last channel you spoke in. If this option is turned off opening the Chat Editbox should always default to the SAY channel."
L["Whisper Alert"] = true;
L['whispers'] = true;
L['yells'] = true;

--Config / Install
L["All keybindings cleared for |cff00ff00%s|r."] = "All keybindings cleared for |cff00ff00%s|r."
L["Binds Discarded"] = "Binds Discarded"
L["Binds Saved"] = "Binds Saved"
L["Caster DPS"] = "Caster DPS"
L["Chat Set"] = "Chat Set"
L['Choose a theme layout you wish to use for your initial setup.'] = true;
L['Classic Pixel'] = true;
L['Classic'] = true;
L["Click the button below to resize your chat frames, unitframes, and reposition your actionbars."] = "Click the button below to resize your chat frames, unitframes, and reposition your actionbars."
L['Config Mode:'] = true;
L["CVars Set"] = "CVars Set"
L["CVars"] = "CVars"
L["ElvUI Installation"] = "ElvUI Installation"
L["Finished"] = "Finished"
L["Grid Size:"] = "Grid Size:"
L["Healer"] = "Healer"
L["High Resolution"] = true;
L["high"] = "high"
L["Importance: |cff07D400High|r"] = "Importance: |cff07D400High|r"
L["Importance: |cffD3CF00Medium|r"] = "Importance: |cffD3CF00Medium|r"
L["Importance: |cffFF0000Low|r"] = "Importance: |cffFF0000Low|r"
L["Install"] = "Install"
L["Installation Complete"] = "Installation Complete"
L["Layout Set"] = "Layout Set"
L["Layout"] = "Layout"
L["Lock"] = "Lock"
L['Low Resolution'] = true;
L["low"] = "low"
L["Movers unlocked. Move them now and click Lock when you are done."] = "Movers unlocked. Move them now and click Lock when you are done."
L["One or more of the changes you have made require a ReloadUI."] = "One or more of the changes you have made require a ReloadUI."
L["One or more of the changes you have made will effect all characters using this addon. You will have to reload the user interface to see the changes you have made."] = "One or more of the changes you have made will effect all characters using this addon. You will have to reload the user interface to see the changes you have made."
L["Physical DPS"] = "Physical DPS"
L["Please click the button below so you can setup variables and ReloadUI."] = "Please click the button below so you can setup variables and ReloadUI."
L["Please click the button below to setup your CVars."] = "Please click the button below to setup your CVars."
L["Please press the continue button to go onto the next step."] = "Please press the continue button to go onto the next step."
L["Resolution Style Set"] = "Resolution Style Set"
L["Resolution"] = "Resolution"
L["Run the installation process."] = "Run the installation process."
L["Setup Chat"] = "Setup Chat"
L["Setup CVars"] = "Setup CVars"
L["Skip Process"] = "Skip Process"
L["Sticky Frames"] = "Sticky Frames"
L["Tank"] = "Tank"
L["The chat windows function the same as Blizzard standard chat windows, you can right click the tabs and drag them around, rename, etc. Please click the button below to setup your chat windows."] = "The chat windows function the same as Blizzard standard chat windows, you can right click the tabs and drag them around, rename, etc. Please click the button below to setup your chat windows."
L["The in-game configuration menu can be accesses by typing the /ec command or by clicking the 'C' button on the minimap. Press the button below if you wish to skip the installation process."] = "The in-game configuration menu can be accesses by typing the /ec command or by clicking the 'C' button on the minimap. Press the button below if you wish to skip the installation process."
L['Theme Set'] = true;
L['Theme Setup'] = true;
L["This install process will help you learn some of the features in ElvUI has to offer and also prepare your user interface for usage."] = "This install process will help you learn some of the features in ElvUI has to offer and also prepare your user interface for usage."
L["This is completely optional."] = "This is completely optional."
L["This part of the installation process sets up your chat windows names, positions and colors."] = "This part of the installation process sets up your chat windows names, positions and colors."
L["This part of the installation process sets up your World of Warcraft default options it is recommended you should do this step for everything to behave properly."] = "This part of the installation process sets up your World of Warcraft default options it is recommended you should do this step for everything to behave properly."
L["This resolution doesn't require that you change settings for the UI to fit on your screen."] = "This resolution doesn't require that you change settings for the UI to fit on your screen."
L["This resolution requires that you change some settings to get everything to fit on your screen."] = "This resolution requires that you change some settings to get everything to fit on your screen."
L["This will change the layout of your unitframes, raidframes, and datatexts."] = "This will change the layout of your unitframes, raidframes, and datatexts."
L["Toggle Anchors"] = "Toggle Anchors"
L['Toggle Configuration'] = true;
L["Unlock various elements of the UI to be repositioned."] = "Unlock various elements of the UI to be repositioned."
L["Using the healer layout it is highly recommended you download the addon Clique to work side by side with ElvUI."] = "Using the healer layout it is highly recommended you download the addon Clique to work side by side with ElvUI."
L["Version"] = "Version"
L["You are now finished with the installation process. Bonus Hint: If you wish to access blizzard micro menu, middle click on the minimap. If you don't have a middle click button then hold down shift and right click the minimap. If you are in need of technical support please visit us at www.tukui.org."] = "You are now finished with the installation process. Bonus Hint: If you wish to access blizzard micro menu, middle click on the minimap. If you don't have a middle click button then hold down shift and right click the minimap. If you are in need of technical support please visit us at www.tukui.org."
L['You can always change fonts and colors of any element of elvui from the in-game configuration.'] = true;
L["You can now choose what layout you wish to use based on your combat role."] = "You can now choose what layout you wish to use based on your combat role."
L["You may need to further alter these settings depending how low you resolution is."] = "You may need to further alter these settings depending how low you resolution is."
L["Your current resolution is %s, this is considered a %s resolution."] = "Your current resolution is %s, this is considered a %s resolution."

--Credits
L["Coding:"] = "Coding:"
L["Donations:"] = "Donations:"
L["ELVUI_CREDITS"] = "I would like to give out a special shout out to the following people for helping me maintain this addon with testing and coding and people who also have helped me through donations. Please note for donations I'm only posting the names of people who PM'd me on the forums, if your name is missing and you wish to have your name added please PM me."
L["Testing:"] = "Testing:"

--DataTexts
L["(Hold Shift) Memory Usage"] = "(Hold Shift) Memory Usage"
L["24-Hour Time"] = "24-Hour Time"
L["AP"] = "AP"
L["AVD: "] = "AVD: "
L["Avoidance Breakdown"] = "Avoidance Breakdown"
L["Bandwidth"] = "Bandwidth"
L['Bases Assaulted'] = true;
L['Bases Defended'] = true;
L['Battleground datatexts temporarily hidden, to show type /bgstats or right click the "C" icon near the minimap.'] = true;
L['Battleground datatexts will now show again if you are inside a battleground.'] = true;
L['Battleground Texts'] = true;
L["Character: "] = true
L["Chest"] = "Chest"
L["DataTexts"] = "DataTexts"
L["DATATEXT_DESC"] = "Setup the on-screen display of info-texts."
L["Deficit:"] = "Deficit:"
L['Demolishers Destroyed'] = true;
L["DPS"] = "DPS"
L["Earned:"] = "Earned:"
L["Feet"] = "Feet"
L['Flags Captured'] = true;
L['Flags Returned'] = true;
L["Friends List"] = "Friends List"
L['Gates Destroyed'] = true;
L['Graveyards Assaulted'] = true;
L['Graveyards Defended'] = true;
L["Hands"] = "Hands"
L["Head"] = "Head"
L["Hit"] = "Hit"
L["Home Latency:"] = "Home Latency:"
L["HP"] = "HP"
L["HPS"] = "HPS"
L["If not set to true then the server time will be displayed instead."] = "If not set to true then the server time will be displayed instead."
L["left"] = "Left"
L["LeftChatDataPanel"] = "Left Chat"
L["LeftMiniPanel"] = "Minimap Left"
L["Legs"] = "Legs"
L["Local Time"] = "Local Time"
L["lvl"] = "lvl"
L["Main Hand"] = "Main Hand"
L["middle"] = "Middle"
L["Offhand"] = "Offhand"
L["Panels"] = "Panels"
L["Profit:"] = "Profit:"
L["right"] = "Right"
L["RightChatDataPanel"] = "Right Chat"
L["RightMiniPanel"] = "Minimap Right"
L["Saved Raid(s)"] = "Saved Raid(s)"
L["Server: "] = "Server: "
L["Session:"] = "Session:"
L["Shoulder"] = "Shoulder"
L['Show BG Texts'] = true;
L["SP"] = "SP"
L["Spent:"] = "Spent:"
L['Stats For:'] = true;
L["Toggle 24-hour mode for the time datatext."] = "Toggle 24-hour mode for the time datatext."
L["Total CPU:"] = "Total CPU:"
L["Total Memory:"] = "Total Memory:"
L["Total: "] = "Total: "
L['Towers Assaulted'] = true;
L['Towers Defended'] = true;
L["Unhittable:"] = "Unhittable:"
L["Waist"] = "Waist"
L['When inside a battleground display personal scoreboard information on the main datatext bars.'] = true;
L["Wrist"] = "Wrist"

--DebugTools
L["%s: %s tried to call the protected function '%s'."] = true;
L["No locals to dump"] = true;
L['|cFFE30000Lua error recieved. You can view the error message when you exit combat.'] = true;

--General
L["Accept Invites"] = "Accept Invites"
L["Adjust the size of the minimap."] = "Adjust the size of the minimap."
L['Always Display'] = true;
L["Announce Interrupts"] = "Announce Interrupts"
L["Announce when you interrupt a spell to the specified chat channel."] = "Announce when you interrupt a spell to the specified chat channel."
L["Auto Repair"] = "Auto Repair"
L["Auto Scale"] = "Auto Scale"
L["Automatically accept invites from guild/friends."] = "Automatically accept invites from guild/friends."
L["Automatically repair using the following method when visiting a merchant."] = "Automatically repair using the following method when visiting a merchant."
L["Automatically scale the User Interface based on your screen resolution"] = "Automatically scale the User Interface based on your screen resolution"
L["Automatically vendor gray items when visiting a vendor."] = "Automatically vendor gray items when visiting a vendor."
L["Backdrop color of transparent frames"] = "Backdrop color of transparent frames"
L["Backdrop Color"] = "Backdrop Color"
L["Backdrop Faded Color"] = "Backdrop Faded Color"
L["Below Minimap"] = "Below Minimap"
L["Border Color"] = "Border Color"
L["Can't Roll"] = "Can't Roll"
L['Change settings for the display of the location text that is on the minimap.'] = true;
L["Change the position of the experience/reputation bar."] = "Change the position of the experience/reputation bar."
L["CombatText Font"] = "CombatText Font"
L["Controls what the transparency of the worldmap will be set to when you are moving."] = "Controls what the transparency of the worldmap will be set to when you are moving."
L["Default Font"] = "Default Font"
L["Disband Group"] = "Disband Group"
L['Display emotion icons in chat.'] = true;
L["Don't scale the large world map to block out sides of the screen."] = true;
L["ELVUI_DESC"] = "ElvUI is a complete User Interface replacement addon for World of Warcraft."
L['Emotion Icons'] = true;
L["Enable/Disable the loot frame."] = "Enable/Disable the loot frame."
L["Enable/Disable the loot roll frame."] = "Enable/Disable the loot roll frame."
L["Exp/Rep Position"] = "Exp/Rep Position"
L["Font Size"] = "Font Size"
L["Fonts"] = "Fonts"
L["General"] = "General"
L["Hide Both"] = "Hide Both"
L["Left Only"] = "Left Only"
L['Location Text'] = true;
L["Log Taints"] = true;
L["Login Message"] = "Login Message"
L["LOGIN_MSG"] = "Welcome to %sElvUI|r version %s%s|r, type /ec to access the in-game configuration menu. If you are in need of technical support you can visit us at www.tukui.org. You can report bugs, add suggestions here: http://www.tukui.org/tickets/elvui/."
L["Loot Roll"] = "Loot Roll"
L["Loot"] = "Loot"
L["Main backdrop color of the UI."] = "Main backdrop color of the UI."
L["Main border color of the UI."] = "Main border color of the UI."
L['Map Alpha While Moving'] = 'Map Alpha While Moving'
L["Media"] = "Media"
L['Minimap Mouseover'] = true;
L['Minimap Panels'] = true;
L["Minimap Size"] = "Minimap Size"
L["Panel Backdrop"] = "Panel Backdrop"
L["Panel Height"] = "Panel Height"
L["Panel Texture (Left)"] = "Panel Texture (Left)"
L["Panel Texture (Right)"] = "Panel Texture (Right)"
L["Panel Width"] = "Panel Width"
L["PANEL_DESC"] = "Adjust the size of your left and right panels, this will effect your chat and bags."
L["Primary Texture"] = "Primary Texture"
L["Reset all frames to their original positions."] = "Reset all frames to their original positions."
L["Reset Anchors"] = "Reset Anchors"
L["Right Only"] = "Right Only"
L["Secondary Texture"] = "Secondary Texture"
L["Send ADDON_ACTION_BLOCKED errors to the Lua Error frame. These errors are less important in most cases and will not effect your game performance. Also a lot of these errors cannot be fixed. Please only report these errors if you notice a Defect in gameplay."] = true;
L["Set the font size for everything in UI. Note: This doesn't effect somethings that have their own seperate options (UnitFrame Font, Datatext Font, ect..)"] = "Set the font size for everything in UI. Note: This doesn't effect somethings that have their own seperate options (UnitFrame Font, Datatext Font, ect..)"
L["Show Both"] = "Show Both"
L["Textures"] = "Textures"
L["The font that combat text will use. |cffFF0000WARNING: This requires a game restart or re-log for this change to take effect.|r"] = "The font that combat text will use. |cffFF0000WARNING: This requires a game restart or re-log for this change to take effect.|r"
L["The font that the core of the UI will use."] = "The font that the core of the UI will use."
L["The texture that will be used mainly for statusbars."] = "The texture that will be used mainly for statusbars."
L["This texture will get used on objects like chat windows and dropdown menus."] = "This texture will get used on objects like chat windows and dropdown menus."
L["Tiny Map"] = true;
L["Toggle showing of the left and right chat panels."] = "Toggle showing of the left and right chat panels."
L['Toggle Tutorials'] = true;
L["Top Screen"] = "Top Screen"
L["Value Color"] = "Value Color"
L["Welcome to ElvUI version %s!"] = "Welcome to ElvUI version %s!"
L["XP:"] = "XP:"
L[ [=[Specify a filename located inside the World of Warcraft directory. Textures folder that you wish to have set as a panel background.

Please Note:
-The image size recommended is 256x128
-You must do a complete game restart after adding a file to the folder.
-The file type must be tga format.

Example: Interface\AddOns\ElvUI\media\textures\copy

Or for most users it would be easier to simply put a tga file into your WoW folder, then type the name of the file here.]=] ] = [=[Specify a filename located inside the World of Warcraft directory. Textures folder that you wish to have set as a panel background.

Please Note:
-The image size recommended is 256x128
-You must do a complete game restart after adding a file to the folder.
-The file type must be tga format.

Example: Interface\AddOns\ElvUI\media\textures\copy

Or for most users it would be easier to simply put a tga file into your WoW folder, then type the name of the file here.]=]

--Misc
L['Bars'] = true;
L["Empty Slot"] = "Empty Slot"
L["Enable"] = "Enable" --Doesn't fit a section since it's used a lot of places
L["Experience"] = "Experience"
L["Fishy Loot"] = "Fishy Loot"
L["INCOMPATIBLE_ADDON"] = "The addon %s is not compatible with ElvUI's %s module. Please disable the incompatible addon or module."
L["Left Click:"] = "Left Click:" --layout\layout.lua
L["Raid Menu"] = "Raid Menu"
L["Remaining:"] = "Remaining:"
L["Rested:"] = "Rested:"
L["Right Click:"] = "Right Click:" --layout\layout.lua
L["Toggle Chat Frame"] = "Toggle Chat Frame" --layout\layout.lua
L["Toggle Embedded Addon"] = "Toggle Embedded Addon" --layout\layout.lua
L["You don't have enough money to repair."] = "You don't have enough money to repair."
L["You don't have permission to mark targets."] = "You don't have permission to mark targets."
L["Your items have been repaired for: "] = "Your items have been repaired for: "
L["Your items have been repaired using guild bank funds for: "] = "Your items have been repaired using guild bank funds for: "
L["Your version of ElvUI is out of date. You can download the latest version from www.tukui.org"] = "Your version of ElvUI is out of date. You can download the latest version from www.tukui.org" --core\core.lua

--NamePlates
L["Add Name"] = "Add Name"
L["All"] = "All"
L["Auras"] = "Auras"
L["Bad Color"] = "Bad Color"
L["Bad Scale"] = "Bad Scale"
L["Bad Transition Color"] = "Bad Transition Color"
L["Castbar Height"] = "Castbar Height"
L['Color the border of the nameplate yellow when it reaches the threshold point on these types of frames.'] = true;
L['Color the border of the nameplate yellow when it reaches this point, it will be colored red when it reaches half this value.'] = true;
L["Color the nameplate's healthbar by your current threat, Example: good threat color is used if your a tank when you have threat, opposite for DPS."] = "Color the nameplate's healthbar by your current threat, Example: good threat color is used if your a tank when you have threat, opposite for DPS."
L["Combat Toggle"] = "Combat Toggle"
L["Controls the height of the nameplate"] = "Controls the height of the nameplate"
L["Controls the height of the nameplate's castbar"] = "Controls the height of the nameplate's castbar"
L["Controls the width of the nameplate"] = "Controls the width of the nameplate"
L["Custom Color"] = "Custom Color"
L["Custom Scale"] = "Custom Scale"
L["Disable threat coloring for this plate and use the custom color."] = "Disable threat coloring for this plate and use the custom color."
L["Discipline"] = "Discipline"
L["Display a healer icon over known healers inside battlegrounds."] = "Display a healer icon over known healers inside battlegrounds."
L["Display level text on nameplate for nameplates that belong to units that aren't your level."] = "Display level text on nameplate for nameplates that belong to units that aren't your level."
L["Display your personal debuffs over the nameplate."] = "Display your personal debuffs over the nameplate."
L["Enemy"] = "Enemy"
L["Enhance Threat"] = "Enhance Threat"
L["Filter already exists!"] = "Filter already exists!"
L["Friendly NPC"] = "Friendly NPC"
L["Friendly Player"] = "Friendly Player"
L["Good Color"] = "Good Color"
L["Good Scale"] = "Good Scale"
L["Good Transition Color"] = "Good Transition Color"
L["Healer Icon"] = "Healer Icon"
L["Hide"] = "Hide"
L["Holy"] = "Holy"
L['Low Health Threshold'] = true;
L['Low Health Warning'] = true;
L["NamePlates"] = "NamePlates"
L["NAMEPLATE_DESC"] = "Modify the nameplate settings."
L["Personal Debuffs"] = "Personal Debuffs"
L['Players'] = true;
L["Prevent any nameplate with this unit name from showing."] = "Prevent any nameplate with this unit name from showing."
L["Remove Name"] = "Remove Name"
L["Restoration"] = "Restoration"
L["Select a filter to use. These are imported from the unitframe aura filter."] = "Select a filter to use. These are imported from the unitframe aura filter." --This one is not visible in the GUI since desc is not used on select groups. Keep for dropdown based menus?
L["Set the scale of the nameplate."] = "Set the scale of the nameplate."
L["This color is displayed when gaining/losing threat, for a tank it would be displayed when gaining threat, for a dps/healer it would be displayed when losing threat"] = "This color is displayed when gaining/losing threat, for a tank it would be displayed when gaining threat, for a dps/healer it would be displayed when losing threat"
L["This color is displayed when gaining/losing threat, for a tank it would be displayed when losing threat, for a dps/healer it would be displayed when gaining threat"] = "This color is displayed when gaining/losing threat, for a tank it would be displayed when losing threat, for a dps/healer it would be displayed when gaining threat"
L["This is displayed when you don't have threat as a tank, if you do have threat it is displayed as a DPS/Healer"] = "This is displayed when you don't have threat as a tank, if you do have threat it is displayed as a DPS/Healer"
L["This is displayed when you have threat as a tank, if you don't have threat it is displayed as a DPS/Healer"] = "This is displayed when you have threat as a tank, if you don't have threat it is displayed as a DPS/Healer"
L["Threat"] = "Threat"
L["Toggles the nameplates off when not in combat."] = "Toggles the nameplates off when not in combat."
L["Use this filter."] = "Use this filter."
L["You can't remove a default name from the filter, disabling the name."] = "You can't remove a default name from the filter, disabling the name."

--Skins
L["Achievement Frame"] = "Achievement Frame"
L["Achievement Frame"] = "Achievement Frame"
L['Alert Frames'] = true;
L["Archaeology Frame"] = "Archaeology Frame"
L["Auction Frame"] = "Auction Frame"
L["Barbershop Frame"] = "Barbershop Frame"
L["BG Map"] = "BG Map"
L["BG Score"] = "BG Score"
L["Calendar Frame"] = "Calendar Frame"
L["Character Frame"] = "Character Frame"
L["Debug Tools"] = "Debug Tools"
L["Dressing Room"] = "Dressing Room"
L["Embedded Addon"] = "Embedded Addon"
L["Embedded Bar Height"] = "Embedded Bar Height"
L["Encounter Journal"] = "Encounter Journal"
L["Focus Frame"] = "Focus Frame"
L["FocusTarget Frame"] = "FocusTarget Frame"
L["Friends"] = "Friends"
L["Glyph Frame"] = "Glyph Frame"
L["Gossip Frame"] = "Gossip Frame"
L["Greeting Frame"] = "Greeting Frame"
L["Guild Bank"] = "Guild Bank"
L["Guild Control Frame"] = "Guild Control Frame"
L["Guild Frame"] = "Guild Frame"
L["Guild Registrar"] = "Guild Registrar"
L["Help Frame"] = "Help Frame"
L["Inspect Frame"] = "Inspect Frame"
L["KeyBinding Frame"] = "KeyBinding Frame"
L["LF Guild Frame"] = "LF Guild Frame"
L["LFG Frame"] = "LFG Frame"
L["Loot Frames"] = true;
L["Macro Frame"] = "Macro Frame"
L["Mail Frame"] = "Mail Frame"
L["Merchant Frame"] = "Merchant Frame"
L["Misc Frames"] = "Misc Frames"
L["Mounts & Pets"] = true;
L["Non-Raid Frame"] = "Non-Raid Frame"
L["Pet Battle"] = true;
L["Pet Frame"] = "Pet Frame"
L["Petition Frame"] = "Petition Frame"
L["PvP Frames"] = "PvP Frames"
L["Quest Frames"] = "Quest Frames"
L["Raid Frame"] = "Raid Frame"
L["Reforge Frame"] = "Reforge Frame"
L["Select an addon to embed to the right chat window. This will resize the addon to fit perfectly into the chat window, it will also parent it to the chat window so hiding the chat window will also hide the addon."] = "Select an addon to embed to the right chat window. This will resize the addon to fit perfectly into the chat window, it will also parent it to the chat window so hiding the chat window will also hide the addon."
L["Skin the blizzard chat bubbles."] = "Skin the blizzard chat bubbles."
L["Skins"] = "Skins"
L["SKINS_DESC"] = "Adjust Skin settings."
L["Socket Frame"] = "Socket Frame"
L['Spacing'] = true;
L["Spellbook"] = "Spellbook"
L["Stable"] = "Stable"
L["Tabard Frame"] = "Tabard Frame"
L["Talent Frame"] = "Talent Frame"
L["Taxi Frame"] = "Taxi Frame"
L["The height of the bars while skada is embedded."] = "The height of the bars while skada is embedded."
L['The spacing in between bars.'] = true;
L["Time Manager"] = "Time Manager"
L["TOGGLESKIN_DESC"] = "Enable/Disable this skin."
L["Trade Frame"] = "Trade Frame"
L["TradeSkill Frame"] = "TradeSkill Frame"
L["Trainer Frame"] = "Trainer Frame"
L["World Map"] = "World Map"

--Static Popups
L["A setting you have changed will change an option for this character only. This setting that you have changed will be uneffected by changing user profiles. Changing this setting requires that you reload your User Interface."] = true;
L["Are you sure you want to delete all your gray items?"] = "Are you sure you want to delete all your gray items?"
L["Are you sure you want to disband the group?"] = "Are you sure you want to disband the group?"
L["Are you sure you want to reset every mover back to it's default position?"] = "Are you sure you want to reset every mover back to it's default position?"
L["Can't buy anymore slots!"] = "Can't buy anymore slots!"
L["Hover your mouse over any actionbutton or spellbook button to bind it. Press the escape key or right click to clear the current actionbutton's keybinding."] = "Hover your mouse over any actionbutton or spellbook button to bind it. Press the escape key or right click to clear the current actionbutton's keybinding."
L["Save"] = "Save"
L["You have changed your UIScale, however you still have the AutoScale option enabled in ElvUI. Press accept if you would like to disable the Auto Scale option."] = "You have changed your UIScale, however you still have the AutoScale option enabled in ElvUI. Press accept if you would like to disable the Auto Scale option."
L["You must purchase a bank slot first!"] = "You must purchase a bank slot first!"

--Tooltip
L["AFK"] = "AFK"
L["Anchor Mode"] = "Anchor Mode"
L["Anchor"] = "Anchor"
L["Combat Hide"] = "Combat Hide"
L["Count"] = "Count"
L["Cursor"] = "Cursor"
L["Don't display the tooltip when mousing over a unitframe."] = "Don't display the tooltip when mousing over a unitframe."
L["Hide tooltip while in combat."] = "Hide tooltip while in combat."
L["Set the type of anchor mode the tooltip should use."] = "Set the type of anchor mode the tooltip should use."
L["Smart"] = "Smart"
L["Targeted By:"] = "Targeted By:"
L["Tooltip"] = "Tooltip"
L["TOOLTIP_DESC"] = "Setup options for the Tooltip."
L["UF Hide"] = "UF Hide"
L["When in a raid group display if anyone in your raid is targetting the current tooltip unit."] = "When in a raid group display if anyone in your raid is targetting the current tooltip unit."
L["Who's targetting who?"] = "Who's targetting who?"

--Tutorials
L['A raid marker feature is available by pressing Escape -> Keybinds scroll to the bottom under ElvUI and setting a keybind for the raid marker.'] = true;
L['ElvUI has a dual spec feature which allows you to load different profiles based on your current spec on the fly. You can enable this from the profiles tab.'] = true;
L['For technical support visit us at www.tukui.org.'] = true;
L['If you accidently remove a chat frame you can always go the in-game configuration menu, press install, go to the chat portion and reset them.'] = true
L['If you are experiencing issues with ElvUI try disabling all your addons except ElvUI, remember ElvUI is a full UI replacement addon, you cannot run two addons that do the same thing.'] = true;
L['If you need to reset the gold datatext type /resetgold.'] = true;
L['If your experience and reputation bars disappear, mouse over the place where they were and click them again.'] = true;
L['The buff panel to the right of minimap is a list of your consolidated buffs. You can disable it in Buffs and Debuffs options of ElvUI.'] = true;
L['The focus unit can be set by typing /focus when you are targetting the unit you want to focus. It is recommended you make a macro to do this.'] = true;
L['To move abilities on the actionbars by default hold shift + drag. You can change the modifier key from the blizzard actionbar options menu.'] = true;
L['To setup which channels appear in which chat frame, right click the chat tab and go to settings.'] = true;
L['Using the /farmmode <size> command will spawn a larger minimap on your screen that can be moved around, very useful when farming.'] = true;
L['You can access copy chat and chat menu functions by mouse over the top right corner of chat panel and left/right click on the button that will appear.'] = true;
L['You can set your keybinds quickly by typing /kb.'] = true;
L['You can toggle the microbar by using your middle mouse button on the minimap you can also accomplish this by holding shift and right clicking on the minimap.'] = true;
L['You can use the /resetui command to reset all of your movers. You can also use the command to reset a specific mover, /resetui <mover name>.\nExample: /resetui Player Frame'] = true;

--UnitFrames
L["%s frame(s) has a conflicting anchor point, please change either the buff or debuff anchor point so they are not attached to each other. Forcing the debuffs to be attached to the main unitframe until fixed."] = "%s frame(s) has a conflicting anchor point, please change either the buff or debuff anchor point so they are not attached to each other. Forcing the debuffs to be attached to the main unitframe until fixed."
L['Above'] = true;
L["Add a spell to the filter."] = "Add a spell to the filter."
L["Add Spell"] = "Add Spell"
L["Add SpellID"] = "Add SpellID"
L['Allow displaying of aura bars that are considered consolidated by Blizzard.'] = true;
L['Allow displaying of aura bars that do not have a duration.'] = true;
L["Alt-Power"] = "Alt-Power" --Not in beta but is in live version
L["An X offset (in pixels) to be used when anchoring new frames."] = "An X offset (in pixels) to be used when anchoring new frames."
L["An Y offset (in pixels) to be used when anchoring new frames."] = "An Y offset (in pixels) to be used when anchoring new frames."
L['Anchor To'] = true;
L["Any Unit"] = "Any Unit"
L["Arena Frames"] = "Arena Frames"
L["Assist Frames"] = "Assist Frames"
L["Attach To"] = "Attach To"
L['Aura Bars'] = true;
L["Bad"] = "Bad"
L["Bars will transition smoothly."] = "Bars will transition smoothly."
L['Below'] = true;
L["Blacklist"] = "Blacklist"
L["Blank"] = "Blank"
L["Boss Frames"] = "Boss Frames"
L["Buff Indicator"] = "Buff Indicator"
L["Buffs"] = "Buffs"
L["Camera Distance Scale"] = "Camera Distance Scale"
L["Castbar"] = "Castbar"
L["Class Backdrop"] = "Class Backdrop"
L["Class Health"] = "Class Health"
L['Class Names'] = true;
L["Class Power"] = "Class Power"
L["Classbar"] = "Classbar"
L["Color health by ammount remaining."] = "Color health by ammount remaining."
L["Color health by classcolor or reaction."] = "Color health by classcolor or reaction."
L["Color Icons"] = "Color Icons"
L["Color power by classcolor or reaction."] = "Color power by classcolor or reaction."
L["Color some texts use."] = "Color some texts use."
L["Color the health backdrop by class or reaction."] = "Color the health backdrop by class or reaction."
L["Color the icon to their set color in the filters section, otherwise use the icon texture."] = "Color the icon to their set color in the filters section, otherwise use the icon texture."
L['Color the name text by class or reaction.'] = true;
L["Color the unit healthbar if there is a debuff that can be dispelled by you."] = "Color the unit healthbar if there is a debuff that can be dispelled by you."
L["Color"] = "Color"
L["Colors"] = "Colors"
L["Column Point"] = "Column Point"
L["Column Spacing"] = "Column Spacing"
L["Combat Fade"] = "Combat Fade"
L["Combobar"] = "Combobar"
L["Copy From"] = "Copy From"
L["Create a filter, once created a filter can be set inside the buffs/debuffs section of each unit."] = "Create a filter, once created a filter can be set inside the buffs/debuffs section of each unit."
L["Create Filter"] = "Create Filter"
L["Credits"] = "Credits"
L["Current - Max"] = "Current - Max"
L["Current - Percent"] = "Current - Percent"
L["Current / Max"] = "Current / Max"
L["Current"] = "Current"
L["Custom Health Backdrop"] = "Custom Health Backdrop"
L["Debuff Highlighting"] = "Debuff Highlighting"
L["Debuffs"] = "Debuffs"
L["Deficit"] = "Deficit"
L["Delete a created filter, you cannot delete pre-existing filters, only custom ones."] = "Delete a created filter, you cannot delete pre-existing filters, only custom ones."
L["Delete Filter"] = "Delete Filter"
L["Direction the health bar moves when gaining/losing health."] = "Direction the health bar moves when gaining/losing health."
L["Disable Blizzard"] = "Disable Blizzard"
L["Disables the blizzard party/raid frames."] = "Disables the blizzard party/raid frames."
L["Disconnected"] = "Disconnected"
L["Display a spark texture at the end of the castbar statusbar to help show the differance between castbar and backdrop."] = "Display a spark texture at the end of the castbar statusbar to help show the differance between castbar and backdrop."
L['Display Frames'] = true;
L["Display Player"] = "Display Player"
L["Display Target"] = "Display Target"
L["Display the rested icon on the unitframe."] = "Display the rested icon on the unitframe."
L["Display the target of the cast on the castbar."] = "Display the target of the cast on the castbar."
L["Display tick marks on the castbar for channelled spells. This will adjust automatically for spells like Drain Soul and add additional ticks based on haste."] = "Display tick marks on the castbar for channelled spells. This will adjust automatically for spells like Drain Soul and add additional ticks based on haste."
L["Down"] = "Down"
L["Duration Limit"] = "Duration Limit"
L["Fade the unitframe when out of combat, not casting, no target exists."] = "Fade the unitframe when out of combat, not casting, no target exists."
L["Fill"] = "Fill"
L["Filled"] = "Filled"
L["Filter Type"] = "Filter Type"
L["Filters"] = "Filters"
L['Force the frames to show, they will act as if they are the player frame.'] = true;
L["Format"] = "Format"
L["Frame"] = "Frame"
L["Frequent Updates"] = "Frequent Updates"
L["Ghost"] = "Ghost"
L["Good"] = "Good"
L["Group By"] = "Group By"
L["Group Point"] = "Group Point"
L["Growth direction of the buffs"] = "Growth direction of the buffs"
L["Growth Direction"] = "Growth Direction"
L["Heal Prediction"] = "Heal Prediction"
L["Health Backdrop"] = "Health Backdrop"
L["Health By Value"] = "Health By Value"
L["Health Text"] = "Health Text"
L["Health"] = "Health"
L["Height"] = "Height"
L['Hold shift + right click to blacklist this aura.'] = true;
L["Horizontal"] = "Horizontal" --Also used in bags module
L["How far away the portrait is from the camera."] = "How far away the portrait is from the camera."
L["Icon"] = "Icon"
L['If not set to 0 then override the size of the aura icon to this.'] = true;
L["If set only auras belonging to yourself in addition to any aura that passes the set filter may be shown."] = "If set only auras belonging to yourself in addition to any aura that passes the set filter may be shown."
L["Initial Anchor"] = "Initial Anchor"
L["Interrupt Color"] = "Interrupt Color"
L["Latency"] = "Latency"
L["Left"] = "Left"
L["Length"] = true;
L["Long (Include Level)"] = true;
L["Long"] = true;
L["Low Mana Threshold"] = "Low Mana Threshold"
L["Main statusbar texture."] = "Main statusbar texture."
L["Match Frame Width"] = "Match Frame Width"
L["Max Columns"] = "Max Columns"
L["Medium"] = true;
L["MT, MA First"] = true;
L["Name"] = "Name"
L["Neutral"] = "Neutral"
L['No Consolidated'] = true;
L['No Duration'] = true;
L["None"] = "None" --Also used in chat
L["Not valid spell id"] = "Not valid spell id"
L["Num Rows"] = "Num Rows"
L["Offline"] = "Offline"
L["Offset of the powerbar to the healthbar, set to 0 to disable."] = "Offset of the powerbar to the healthbar, set to 0 to disable."
L["Offset"] = "Offset"
L["OOR Alpha"] = "OOR Alpha"
L["Orientation"] = "Orientation"
L["Overlay the healthbar"] = "Overlay the healthbar"
L["Overlay"] = "Overlay"
L["Override any custom visibility setting in certain situations, EX: Only show groups 1 and 2 inside a 10 man instance."] = "Override any custom visibility setting in certain situations, EX: Only show groups 1 and 2 inside a 10 man instance."
L["Party Frames"] = "Party Frames"
L["Party Pets"] = "Party Pets"
L["Party Targets"] = "Party Targets"
L["Per Row"] = "Per Row"
L["Percent"] = "Percent"
L["Personal Auras"] = "Personal Auras"
L["PetTarget Frame"] = "PetTarget Frame"
L["Player Frame"] = "Player Frame"
L["Portrait"] = "Portrait"
L["Position"] = "Position"
L["Power text will be hidden on NPC targets, in addition the name text will be repositioned to the power texts anchor point."] = "Power text will be hidden on NPC targets, in addition the name text will be repositioned to the power texts anchor point."
L["Power"] = "Power"
L["Powers"] = "Powers"
L["Priority"] = true;
L['Raid-10 Frames'] = true;
L['Raid-25 Frames'] = true;
L['Raid-40 Frames'] = true;
L["RaidDebuff Indicator"] = "RaidDebuff Indicator"
L["Rapidly update the health, uses more memory and cpu. Only recommended for healing."] = "Rapidly update the health, uses more memory and cpu. Only recommended for healing."
L["Reactions"] = "Reactions"
L["Remaining"] = "Remaining"
L["Remove a spell from the filter."] = "Remove a spell from the filter."
L["Remove Spell"] = "Remove Spell"
L["Remove SpellID"] = "Remove SpellID"
L["Rest Icon"] = "Rest Icon"
L["Restore Defaults"] = "Restore Defaults" --Also used in General and ActionBars sections
L["Right"] = "Right"
L['RL / ML Icons'] = true;
L["Role Icon"] = "Role Icon"
L["Select a filter to use."] = "Select a filter to use." --Also used in NamePlates
L["Select a unit to copy settings from."] = "Select a unit to copy settings from."
L["Select Filter"] = "Select Filter"
L["Select Spell"] = "Select Spell"
L["Set the filter type, blacklisted filters hide any aura on the like and show all else, whitelisted filters show any aura on the filter and hide all else."] = "Set the filter type, blacklisted filters hide any aura on the like and show all else, whitelisted filters show any aura on the filter and hide all else."
L["Set the font size for unitframes."] = "Set the font size for unitframes."
L["Set the order that the group will sort."] = "Set the order that the group will sort."
L["Set the priority order of the spell, please note that prioritys are only used for the raid debuff module, not the standard buff/debuff module. If you want to disable set to zero."] = true;
L["Short"] = true;
L["Show a incomming heal prediction bar on the unitframe. Also display a slightly different colored bar for incoming overheals."] = "Show a incomming heal prediction bar on the unitframe. Also display a slightly different colored bar for incoming overheals."
L['Show Auras'] = true;
L["Show Party"] = "Show Party"
L["Show Raid"] = "Show Raid"
L["Show Solo"] = "Show Solo"
L["Size of the indicator icon."] = "Size of the indicator icon."
L['Size Override'] = true;
L["Size"] = "Size"
L["Smart Raid Filter"] = "Smart Raid Filter"
L["Smooth Bars"] = "Smooth Bars"
L["Spaced"] = "Spaced"
L["Spark"] = "Spark"
L["Spell not found in list."] = "Spell not found in list."
L["StatusBar Texture"] = "StatusBar Texture"
L["Tank Frames"] = "Tank Frames"
L["Tapped"] = "Tapped"
L["Target Frame"] = "Target Frame"
L["TargetTarget Frame"] = "TargetTarget Frame"
L["Text Format"] = "Text Format"
L["Text Toggle On NPC"] = "Text Toggle On NPC"
L["Text"] = "Text"
L["The alpha to set units that are out of range to."] = "The alpha to set units that are out of range to."
L["The amount of space (in pixels) between the columns."] = "The amount of space (in pixels) between the columns."
L["The anchor point for each new column. A value of LEFT will cause the columns to grow to the right."] = "The anchor point for each new column. A value of LEFT will cause the columns to grow to the right."
L["The aura must be below this duration for the buff to show, set to 0 to disable. Note: This is in seconds."] = "The aura must be below this duration for the buff to show, set to 0 to disable. Note: This is in seconds."
L["The following macro must be true in order for the group to be shown, in addition to any filter that may already be set."] = "The following macro must be true in order for the group to be shown, in addition to any filter that may already be set."
L["The font that the unitframes will use."] = "The font that the unitframes will use."
L["The initial anchor point of the buffs on the frame"] = "The initial anchor point of the buffs on the frame"
L["The maximum number of columns that the header will create."] = "The maximum number of columns that the header will create."
L["The maximum number of units that will be displayed in a single column."] = "The maximum number of units that will be displayed in a single column."
L['The object you want to attach to.'] = true;
L['The point of which you are anchoring to in relation to the attach to object.'] = true;
L['The spell "%s" has been added to the DebuffBlacklist unitframe filter.'] = true;
L["Ticks"] = "Ticks"
L["Toggles health text display"] = "Toggles health text display"
L["UnitFrames"] = "UnitFrames"
L["Units Per Column"] = "Units Per Column"
L["Up"] = "Up"
L["Use Filter"] = "Use Filter"
L["Use the custom health backdrop color instead of a multiple of the main health color."] = "Use the custom health backdrop color instead of a multiple of the main health color."
L["Value must be a number"] = "Value must be a number"
L["Vertical"] = "Vertical" --Also used in bags section
L["Visibility"] = "Visibility"
L["What each frame should attach itself to, example setting it to TOP every unit will attach its top to the last point bottom."] = "What each frame should attach itself to, example setting it to TOP every unit will attach its top to the last point bottom."
L["What point to anchor to the frame you set to attach to."] = "What point to anchor to the frame you set to attach to."
L["What to attach the buff anchor frame to."] = "What to attach the buff anchor frame to."
L["When true, the group header is shown when the player is in a party."] = "When true, the group header is shown when the player is in a party."
L["When true, the group header is shown when the player is in a raid."] = "When true, the group header is shown when the player is in a raid."
L["When true, the header includes the player when not in a raid."] = "When true, the header includes the player when not in a raid."
L["When true, the header is shown when the player is not in any group."] = "When true, the header is shown when the player is not in any group."
L["When you mana falls below this point, text will flash on the player frame."] = "When you mana falls below this point, text will flash on the player frame."
L["Whitelist"] = "Whitelist"
L["Width"] = "Width" --Also used in NamePlates module
L["X-Growth"] = "X-Growth"
L["xOffset"] = "xOffset"
L["Y-Growth"] = "Y-Growth"
L["yOffset"] = "yOffset" --Another variation in bags section Y Offset
L["You can't remove a pre-existing filter."] = "You can't remove a pre-existing filter."
L["You cannot copy settings from the same unit."] = "You cannot copy settings from the same unit."
L["You cannot set the Group Point and Column Point so they are opposite of each other."] = "You cannot set the Group Point and Column Point so they are opposite of each other."
L["You may not remove a spell from a default filter that is not customly added. Setting spell to false instead."] = "You may not remove a spell from a default filter that is not customly added. Setting spell to false instead."

-------------------------------------------------
------Locales that don't appear to be used.------
-------------------------------------------------
L["Achievement Popup Frames"] = "Achievement Popup Frames" --This appears in live but not beta
L["New ID"] = "New ID"
L["Only check if the buff is coming from you."] = "Only check if the buff is coming from you."
L["Personal Buffs"] = "Personal Buffs"
L["Remove Group"] = "Remove Group"
L["Remove ID"] = "Remove ID"
L["Spell already exists in filter."] = "Spell already exists in filter."
L["Spell not found in list"] = "Spell not found in list" --duplicate exists which ends with a "." (dot) and is used in UnitFrames
L["Spell not found."] = "Spell not found."
L["Spells"] = "Spells"
L["Target"] = "Target"
L["This can't be right, you must of broke something! Please turn on lua errors and report the issue to Elv http://www.tukui.org/forums/forum.php?id=146"] = "This can't be right, you must of broke something! Please turn on lua errors and report the issue to Elv http://www.tukui.org/forums/forum.php?id=146"
L["You cannot remove a spell that is default, disabling the spell for you however."] = "You cannot remove a spell that is default, disabling the spell for you however."
-------------------------------------------------
-------------------------------------------------