local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("ElvUI", "ruRU")
if not L then return; end

--ActionBars
L["ActionBars"] = "Панели команд"
L["Action Paging"] = "Переключение панелей"
L["All keybindings cleared for |cff00ff00%s|r."] = "Сброшены все назначения для |cff00ff00%s|r."
L["Anchor Point"] = "Точка фиксации"
L["Backdrop"] = "Фон"
L["Bar "] = "Панель "
L["Binding"] = "Назначение"
L["Binds Discarded"] = "Назначения отменены"
L["Binds Saved"] = "Назначения сохранены"
L["Buttons"] = "Кнопок"
L["Buttons Per Row"] = "Кнопок в ряду"
L["Button Size"] = "Размер кнопок"
L["Button Spacing"] = "Отступ кнопок"
L[" |cff00ff00bound to |r"] = " |cff00ff00назначено для |r"
L["Color when the text is about to expire"] = "Цвет текста почти завершившегося восстановления."
L["Color when the text is in the days format."] = "Цвет текста времени восстановления в днях."
L["Color when the text is in the hours format."] = "Цвет текста времени восстановления в часах."
L["Color when the text is in the minutes format."] = "Цвет текста времени восстановления в минутах."
L["Color when the text is in the seconds format."] = "Цвет текста времени восстановления в секундах."
L["Cooldown Text"] = "Текст восстановления"
L["Days"] = "Дни"
L["Discard"] = "Отменить"
L["Display bind names on action buttons."] = "Отображать назначенные клавиши на кнопках."
L["Display cooldown text on anything with the cooldown spiril."] = "Отображать время восстановления на кнопках/предметах."
L["Display macro names on action buttons."] = "Отображать названия макросов на кнопках."
L["Expiring"] = "Завершение"
L["Height Multiplier"] = "Множитель высоты"
L["Hours"] = "Часы"
L["Key"] = "Клавиша"
L["Keybind Mode"] = "Назначить клавиши"
L["Keybind Text"] = "Текст клавиш"
L["KEY_ALT"] = "A"
L["KEY_BUTTON3"] = "M3"
L["KEY_CTRL"] = "C"
L["KEY_DELETE"] = "Del"
L["KEY_HOME"] = "Hm"
L["KEY_INSERT"] = "Ins"
L["KEY_MOUSEBUTTON"] = "M"
L["KEY_MOUSEWHEELDOWN"] = "MwD"
L["KEY_MOUSEWHEELUP"] = "MwU"
L["KEY_NUMPAD"] = "N"
L["KEY_PAGEDOWN"] = "PD"
L["KEY_PAGEUP"] = "PU"
L["KEY_SHIFT"] = "S"
L["KEY_SPACE"] = "SpB"
L["LOCK_AB_ERROR"] = "Мы заметили, что у вас не заблокированы панели действий. Это может вызвать срабатывание способностей при переносе их в другой слот. Пожалуйста, выполните установку настроек по умолчанию в установке (шаг 2). Это можно сделать, набрав /ес и нажав кнопку Установка."
L["Low Threshold"] = "Минимальное значение"
L["Macro Text"] = "Названия макросов"
L['Max Paging'] = "Макс-ное переключение"
L["Minutes"] = "Минуты"
L["Multiply the backdrops height or width by this value. This is usefull if you wish to have more than one bar behind a backdrop."] = "Умножает высоту или ширину фона панели на это значение. Это полезно, когда Вы хотите иметь более одной панели на данном фоне."
L["No bindings set."] = "Нет назначений"
L["Pet Bar"] = "Панель питомца"
L["Restore Bar"] = "Восстановить панель"
L["Restore the actionbars default settings"] = "Восстанавливает настройки панели по умолчанию."
L["Seconds"] = "Секунды"
L["Set the font size of the action buttons."] = "Устанавливает размер шрифта на кнопках."
L["ShapeShift Bar"] = "Панель стоек"
L["The ammount of buttons to display per row."] = "Количество кнопок в каждом ряду"
L["The ammount of buttons to display."] = "Количество отображаемых кнопок."
L["The first button anchors itself to this point on the bar."] = "Первая кнопка прикрепляется к этой точке панели"
L["The size of the action buttons."] = "Размер кнопок панели команд."
L["Threshold before text turns red and is in decimal form. Set to -1 for it to never turn red"] = "Время, после которого текст станет красным и начнет отображать доли секунды. Установите -1, чтобы не отображать текст в такой форме."
L["Toggles the display of the actionbars backdrop."] = "Включить отображение фона панели команд."
L["Visibility State"] = "Статус отображения"
L['When enabled the main actionbar will use the maximum amount of pages available. This means if you have another actionbar disabled, the actionbar page will become available on the main actionbar. Having this disabled will limit the main actionbar to two pages.'] = "При активации основная панель будет использовать максимальное кол-во панелей для переключения. Это означает, что если какая-то из панелей отключена, то она будет доступна для переключения. Отключение опции ограничит переключение двумя панелями."
L["Width Multiplier"] = "Множитель ширины"
L[ [=[This works like a macro, you can run different situations to get the actionbar to page differently.
 Example: '[combat] 2;']=] ] = [=[Работает как макрос. Вы можете установить различные условия для отображения разных панелей.
 Пример: '[combat] 2;']=]
L[ [=[This works like a macro, you can run different situations to get the actionbar to show/hide differently.
 Example: '[combat] show;hide']=] ] = [=[Работает как макрос. Вы можете установить различные условия для показа/скрытия панели.
 Пример: '[combat] show;hide']=]

--Bags
L["Ascending"] = "Восходящее"
L["Bag-Bar"] = "Панель сумок"
L["Bags"] = "Сумки"
L["BAGS_DESC"] = "Настройки сумок ElvUI"
L["Bag Columns"] = "Столбцов в сумке"
L["Bank Columns"] = "Столбцов в банке"
L["Bar Direction"] = "Направление панели"
L["Bottom to Top"] = "Снизу вверх"
L["Can't buy anymore slots!"] = "Невозможно приобрести больше слотов!"
L["Click to search.."] = "Нажмите для поиска"
L["copperabbrev"] = "|cffeda55fм|r"
L["Delete Grays"] = "Удалить предметы серого качества"
L["Deleted %d gray items. Total Worth: %s"] = "Удалено %d предметов серого качества. Общая стоимость: %s"
L["Descending"] = "Нисходящее"
L["Direction the bag sorting will use to allocate the items."] = "Направление расположения предметов при сортировке."
L["Enable Bag-Bar"] = "Включить панель сумок"
L["Enable/Disable the all-in-one bag."] = 'Включить/выключить режим сумки "все в одной". '
L["Enable/Disable the Bag-Bar."] = "Включить/выключить панель сумок"
L["goldabbrev"] = "|cffffd700з|r"
L["Hold Shift:"] = "С зажатым shift'ом:"
L["No gray items to delete."] = "Нет предметов серого качества для удаления."
L["No gray items to sell."] = "Нет предметов серого качества для продажи."
L["Number of columns (width) of bags. Set it to 0 to match the width of the chat panels."] = "Количество столбцов (ширина окна) в сумках. Установите на 0 для соответствия ширине панелей чата."
L["Number of columns (width) of the bank. Set it to 0 to match the width of the chat panels."] = "Количество столбцов (ширина окна) в банке. Установите на 0 для соответствия ширине панелей чата."
L["Purchase"] = "Приобрести слот"
L["Set the size of your bag buttons."] = "Установите размер кнопок на панели."
L["silverabbrev"] = "|cffc7c7cfс|r"
L["Sort Bags"] = "Сортировать"
L["Sort Direction"] = "Направление сортировки"
L["Sort Orientation"] = "Ориентация сортировки"
L["Sort Special"] = "Сортировать в сумках профессий"
L["Stack Items"] = "Собрать предметы"
L["Stack Special"] = "Собрать в сумках профессий"
L["The direction that the bag frames be (Horizontal or Vertical)."] = "Расположение сумок (горизонтально или вертикально)"
L["The direction that the bag frames will grow from the anchor."] = "Направление, в котором будут расположены кнопки сумок относительно фиксатора."
L["The frame is not shown unless you mouse over the frame."] = "Отображать только при наведении мыши."
L["The spacing between buttons."] = "Расстояние между кнопками"
L["Toggle Bags"] = "Показать сумки"
L["Top to Bottom"] = "Сверху вниз"
L["Vendor Grays"] = "Продавать серые предметы"
L["Vendored gray items for:"] = "Проданы серые предметы на сумму:"
L["X Offset"] = "Отступ по Х"
L["Y Offset"] = "Отступ по Y"
L["You must be at a vendor."] = "Вы должны находиться у торговца"

--Buffs and Debuffs
L['AURAS_DESC'] = 'Настройка иконок эффектов, находящихся у миникарты.'
L['Begin a new row or column after this many auras.'] = "Начинать новый ряд/столбец после этого количества аур."
L['Consolidated Buffs'] = "Объединенные эффекты"
L['Defines how the group is sorted.'] = "Определяет условия сортировки"
L['Defines the sort order of the selected sort method.'] = "Определяет порядок в выбранном методе сортировки."
L['Display the consolidated buffs bar.'] = "Отображать полосу объединенных эффектов."
L['Index'] = "Порядок наложения"
L['Indicate whether buffs you cast yourself should be separated before or after.'] = "Определяет должны ли Ваши баффы находиться отдельно перед или после остальных."
L['Limit the number of rows or columns.'] = "Определяет максимальное количество рядов/столбцов."
L['Max Wraps'] = "Максимум рядов"
L['Name'] = "Имя"
L['No Sorting'] = "Без сортировки"
L["Other's First"] = "Сначала чужие"
L['Seperate'] = "Разделение"
L['Set the size of the individual auras.'] = "Устанавливает размер аур"
L['Sort Method'] = "Метод сортировки"
L['Time'] = "Время"
L['Wrap After'] = "Размер ряда"
L['X Spacing'] = "Отступ по X"
L['Y Spacing'] = "Отступ по Y"
L['Your Auras First'] = "Сначала свои"

--Chat
L["AFK"] = "АФК"
L["Attempt to create URL links inside the chat."] = "Пытаться создавать интернет-ссылки в чате."
L["BG"] = "ПБ"
L["BGL"] = "Лидер ПБ"
L["Chat"] = "Чат"
L["CHAT_DESC"] = "Настройте отображение чата ElvUI."
L["Copy Text"] = "Копировать текст"
L['Display emotion icons in chat.'] = "Показывать смайлы в чате"
L["Display the hyperlink tooltip while hovering over a hyperlink."] = "Отображать подсказку ссылки на при наведении на нее мыши. Действует на предметы, достижения, сохранения подземелий и тд."
L["DND"] = "ДНД"
L['Emotion Icons'] = "Иконки эмоций";
L["Font"] = "Шрифт"
L["Font Outline"] = "Обводка шрифта"
L["G"] = "Г"
L["Hyperlink Hover"] = "Подсказка над ссылками"
L["Keyword Alert"] = "Звук ключевых слов"
L['Keywords'] = "Ключевые слова"
L['List of words to color in chat if found in a message. If you wish to add multiple words you must seperate the word with a comma. To search for your current name you can use %MYNAME%.\n\nExample:\n%MYNAME%, ElvUI, RBGs, Tank'] = "Список слов для окрашивания, если они обнаружены в чате. Если Вы хотите добавить несколько слов, то разделяйте их запятыми. Для поиска имени Вашего текущего персонажа используйте %MYNAME%.\n\nПример:\n%MYNAME%, ElvUI, РБГ, Танк"
L["Number of time in seconds to scroll down to the bottom of the chat window if you are not scrolled down completely."] = "Время в секундах, через которое чат автоматически покрутится вниз до конца, если Вы не сделаете это вручную."
L["O"] = "Оф"
L["P"] = "Гр"
L["PG"] = "Гр"
L["PL"] = "Лидер гр."
L["Prevent the same messages from displaying in chat more than once within this set amount of seconds, set to zero to disable."] = "Предотвращает появление одинаковых сообщения в чате чаще указанного количества секунд. Установите на нуль для отключения."
L["R"] = "Р"
L["RL"] = "РЛ"
L["RW"] = "Объявление"
L['says'] = "говорит"
L["Scroll Interval"] = "Интервал прокрутки"
L["Set the font outline."] = "Устанавливает обводку шрифта."
L["Short Channels"] = "Короткие каналы"
L["Shorten the channel names in chat."] = "Сокращать названия каналов чата."
L["Spam Interval"] = "Интервал спама"
L["Sticky Chat"] = "Клейкий чат"
L["URL Links"] = "Интернет-ссылки"
L["When opening the Chat Editbox to type a message having this option set means it will retain the last channel you spoke in. If this option is turned off opening the Chat Editbox should always default to the SAY channel."] = "При открытии строки ввода сообщения, если эта опция включена, будет выбран последний канал, в который Вы писали. В противном случае всегда будет установлен канал 'сказать'."
L["Whisper Alert"] = "Звук шепота"
L['whispers'] = "шепчет"
L['yells'] = "кричит"

--Config / Install
L["Caster DPS"] = "Заклинатель"
L['Change settings for the display of the location text that is on the minimap.'] = "Изменяет опции отображения названия локации на миникарте"
L["Chat Set"] = "Чат настроен"
L['Choose a theme layout you wish to use for your initial setup.'] = "Выберите тему, которую Вы хотите использовать."
L['Classic'] = "Классическая"
L['Classic Pixel'] = "Пиксельная"
L["Click the button below to resize your chat frames, unitframes, and reposition your actionbars."] = "Нажмите кнопку ниже для изменения размеров вашего чата, рамок юнитов и перемещения ваших панелей действий."
L["CVars"] = "Настройки игры"
L["CVars Set"] = "Настройки сброшены"
L["ElvUI Installation"] = "Установка ElvUI"
L["Finished"] = "Завершить"
L["Grid Size:"] = "Размер сетки"
L["Healer"] = "Лекарь"
L["High Resolution"] = "Высокое разрешение"
L["high"] = "высоким"
L["Importance: |cff07D400High|r"] = "Важность: |cff07D400Высокая|r"
L["Importance: |cffD3CF00Medium|r"] = "Важность: |cffD3CF00Средняя|r"
L["Importance: |cffFF0000Low|r"] = "Важность: |cffFF0000Низкая|r"
L["Install"] = "Установка"
L["Installation Complete"] = "Установка завершена"
L["Layout"] = "Расположение"
L["Layout Set"] = "Расположение установлено"
L["Lock"] = "Закрепить"
L['Low Resolution'] = "Низкое разрешение"
L["low"] = "низким"
L["Movers unlocked. Move them now and click Lock when you are done."] = "Блокировка отключена. Передвиньте фреймы и нажмите 'Закрепить', когда закончите."
L["One or more of the changes you have made will effect all characters using this addon. You will have to reload the user interface to see the changes you have made."] = true;
L["Physical DPS"] = "Физический урон"
L["Please click the button below so you can setup variables and ReloadUI."] = "Пожалуйста, нажмите кнопку ниже для установки переменных и перезагрузки интерфейса."
L["Please click the button below to setup your CVars."] = "Пожалуйста, нажмите кнопку ниже для сброса настроек."
L["Please press the continue button to go onto the next step."] = "Пожалуйста, нажмите кнопку 'Продолжить' для перехода к следующему шагу"
L["Resolution"] = "Разрешение"
L["Resolution Style Set"] = "Разрешение установлено"
L["Run the installation process."] = "Запустить процесс установки"
L["Setup Chat"] = "Настроить чат"
L["Setup CVars"] = "Сбросить настройки"
L["Skip Process"] = "Пропустить установку"
L["Sticky Frames"] = "Клейкие фреймы"
L["Tank"] = "Танк"
L["The chat windows function the same as Blizzard standard chat windows, you can right click the tabs and drag them around, rename, etc. Please click the button below to setup your chat windows."] = "Окна чата работают так же, как и в стандартном чате Blizzard. Вы можете нажать правую кнопку мыши на вкладках для перемещения, переименования и тд. Пожалуйста, нажмите кнопку ниже для настройки чата."
L["The in-game configuration menu can be accesses by typing the /ec command or by clicking the 'C' button on the minimap. Press the button below if you wish to skip the installation process."] = "Меню настроек можно вызвать командой /ес или кнопкой 'С' на миникарте. Нажмите кнопку ниже, если Вы хотите прервать процесс установки."
L['Theme Set'] = "Тема установлена";
L['Theme Setup'] = "Тема";
L["This install process will help you learn some of the features in ElvUI has to offer and also prepare your user interface for usage."] = "Этот процесс установки поможет Вам узнать о некоторых функциях ElvUI и подготовить Ваш интерфейс к использованию."
L["This is completely optional."] = "Это действие абсолютно не обязательно."
L["This part of the installation process sets up your chat windows names, positions and colors."] = "Эта часть установки настроит названия, позиции и цвета вкладок чата."
L["This part of the installation process sets up your World of Warcraft default options it is recommended you should do this step for everything to behave properly."] = "Эта часть установки сбросит настройки World of Warcraft на конфигурацию по умолчанию. Рекомендуется выполнить этот шаг для надлежащей работы интерфейса."
L["This resolution doesn't require that you change settings for the UI to fit on your screen."] = "Для соответствия интерфейса вашему экрану не требуется изменения настроек."
L["This resolution requires that you change some settings to get everything to fit on your screen."] = "Для соответствия интерфейса вашему экрану требуется изменение некоторых настроек."
L["This will change the layout of your unitframes, raidframes, and datatexts."] = "Это изменит расположение ваших рамок юнитов, рейда и информационных текстов"
L["Toggle Anchors"] = "Показать фиксаторы"
L['Toggle Configuration'] = "Конфигурация"
L["Unlock various elements of the UI to be repositioned."] = "Разблокировать элементы интерфейса для их перемещения."
L["Using the healer layout it is highly recommended you download the addon Clique to work side by side with ElvUI."] = "Для использования настроек лекаря крайне рекомендуется установка аддона Clique который всесторонне поддерживается ElvUI."
L["Version"] = "Версия"
L["You are now finished with the installation process. Bonus Hint: If you wish to access blizzard micro menu, middle click on the minimap. If you don't have a middle click button then hold down shift and right click the minimap. If you are in need of technical support please visit us at www.tukui.org."] = "Вы завершили процесс установки. Если Вам требуется техническая поддержка, посетите сайт www.tukui.org. Дополнительный совет: если Вы хотите получить доступ к микроменю blizzard, нажмите средней кнопкой мыши на миникарте. Если у вас нет средней кнопки, то нажмите правой с зажатой клавишей shift."
L['You can always change fonts and colors of any element of elvui from the in-game configuration.'] = "Вы всегда можете изменить шрифты и цвета любого элемента ElvUI из меню конфигурации. Классическая и пиксельная темы не отличаются для русского клиента."
L["You can now choose what layout you wish to use based on your combat role."] = "Вы можете выбрать используемое расположение, основываясь на Вашей роли."
L["You may need to further alter these settings depending how low you resolution is."] = "Вам может понадобиться дальнейшее изменение этих настроек в зависимости от того, насколько низким является ваше разрешение."
L["Your current resolution is %s, this is considered a %s resolution."] = "Ваше текущее разрешение - %s, это считается %s разрешением."

--Credits
L["Coding:"] = "Написание кода:"
L["Credits"] = "Благодарности"
L["Donations:"] = "Финансовая поддержка:"
L["ELVUI_CREDITS"] = "Я бы хотел выделить следующих людей, которые помогли мне в разработке аддона тестированием, кодингом и поддержкой при помощи донаций. Пожалуйста, отметьте, что в разделе донаций я написал имена людей, написавших мне в ЛС на форуме. Если Ваше имя пропущено, и Вы хотите его видеть, отправьте мне сообщение."
L["Testing:"] = "Тестирование:"

--DataTexts
L["24-Hour Time"] = "24х часовой формат"
L["AP"] = "Сила Ат."
L["AVD: "] = "Защита: "
L["Avoidance Breakdown"] = "Распределение защиты"
L["Bandwidth"] = "Канал"
L['Bases Assaulted'] = "Штурмы баз"
L['Bases Defended'] = "Оборона баз"
L['Battleground datatexts temporarily hidden, to show type /bgstats or right click the "C" icon near the minimap.'] = 'Информация поля боя временно скрыта. Для отображения введите /bgstat или ПКМ на иконке "С" у миникарты.'
L['Character:'] = "Персонаж: "
L["Chest"] = "Грудь"
L["DATATEXT_DESC"] = "Установка отображения информационных текстов."
L["DataTexts"] = "Инфо-тексты"
L["Deficit:"] = "Убыток:"
L["DPS"] = "УВС"
L["Earned:"] = "Заработано"
L["Feet"] = "Ступни"
L['Flags Captured'] = "Захваты флага"
L['Flags Returned'] = "Возвраты флага"
L["Friends List"] = "Список друзей"
L['Gates Destroyed'] = "Врат разрушено"
L['Graveyards Assaulted'] = "Штурмы кладбищ"
L['Graveyards Defended'] = "Оборона кладбищ"
L["Hands"] = "Кисти рук"
L["Head"] = "Голова"
L["Hit"] = "Метк."
L["Home Latency:"] = "Локальная задержка: "
L["HP"] = "+ Исцел."
L["HPS"] = "ИВС"
L["If not set to true then the server time will be displayed instead."] = "Если отключено, будет отображаться серверное время."
L["left"] = "Слева"
L["LeftChatDataPanel"] = "Левая панель чата"
L["LeftMiniPanel"] = "Миникарта, слева"
L["Legs"] = "Ноги"
L["Local Time"] = "Местное время"
L["lvl"] = "ур."
L["Main Hand"] = "Правая рука"
L["middle"] = "В центре"
L["Offhand"] = "Левая рука"
L["Panels"] = "Панели"
L["Profit:"] = "Прибыль:"
L["right"] = "Справа"
L["RightChatDataPanel"] = "Правая панель чата"
L["RightMiniPanel"] = "Миникарта, справа"
L["Saved Raid(s)"] = "Сохраненные рейды"
L["Server: "] = "На сервере:"
L["Session:"] = "За сеанс:"
L["Shoulder"] = "Плечо"
L['Show BG Texts'] = "Показать текст ПБ"
L["SP"] = "+ Закл."
L["Spent:"] = "Потрачено:"
L['Stats For:'] = "Статистика для:"
L["Toggle 24-hour mode for the time datatext."] = "Включить 24х часовой формат отображения времени."
L["Total: "] = "Всего:"
L["Total CPU:"] = "Использование процессора:"
L["Total Memory:"] = "Всего памяти: "
L['Towers Assaulted'] = "Штурмы башен"
L['Towers Defended'] = "Оборона башен"
L["Unhittable:"] = "Полная защита от ударов"
L["Waist"] = "Пояс"
L['When inside a battleground display personal scoreboard information on the main datatext bars.'] = "На полях боя отображать личную информацию на основных полосах инфо-текстов";
L["Wrist"] = "Запястья"

--DebugTools
L["%s: %s tried to call the protected function '%s'."] = true;
L["INCOMPATIBLE_ADDON"] = "Аддон %s не совместим с модулем %s ElvUI. Пожалуйста, отключите не совместимый аддон или модуль."
L["No locals to dump"] = true;
L['|cFFE30000Lua error recieved. You can view the error message when you exit combat.'] = "|cFFE30000Обнаружена ошибка lua. Вы получите отчет о ней после завершения боя."

--General
L["Accept Invites"] = "Принимать приглашения"
L["Adjust the size of the minimap."] = "Изменяет размер миникарты"
L['Always Display'] = "Всегда отображать"
L["Announce Interrupts"] = "Объявлять о прерываниях"
L["Announce when you interrupt a spell to the specified chat channel."] = "Объявлять о прерванных Вами заклинаниях в указанный канал чата."
L["An X offset (in pixels) to be used when anchoring new frames."] = "Отступ по оси Х (в пикселях) при добавлении новых рамок"
L["Automatically accept invites from guild/friends."] = "Автоматически принимать приглашения в группу от друзей и гильдии."
L["Automatically repair using the following method when visiting a merchant."] = "Автоматически чинить экипировку за счет выбранного источника при посещении торговца."
L["Automatically scale the User Interface based on your screen resolution"] = "Автоматически масштабировать UI в зависимости от вашего разрешения"
L["Automatically vendor gray items when visiting a vendor."] = "Автоматически продавать предметы серого качества при посещении торговца."
L["Auto Repair"] = "Автоматический ремонт"
L["Auto Scale"] = "Автоматический масштаб"
L["Backdrop Color"] = "Цвет фона"
L["Backdrop color of transparent frames"] = "Цвет фона прозрачных фреймов"
L["Backdrop Faded Color"] = "Цвет прозрачного фона"
L["Below Minimap"] = "Под миникартой"
L["Border Color"] = "Цвет окантовки"
L["Change the position of the experience/reputation bar."] = "Изменяет положение полосы опыта/репутации."
L["Chat Bubbles"] = "Облачка сообщений"
L["Colors"] = "Цвета"
L["Color some texts use."] = "Цвет некоторых текстов."
L["CombatText Font"] = "Шрифт текста боя"
L['Config Mode:'] = "Режим настройки:"
L["Controls what the transparency of the worldmap will be set to when you are moving."] = "Устанавливает прозрачность карты мира при движении персонажа."
L["Default Font"] = "Шрифт по умолчанию"
L["Disband Group"] = "Распустить группу" --RU button
L['Display minimap panels below the minimap, used for datatexts.'] = "Отображать панели информационных текстов под миникартой."
L["Don't scale the large world map to block out sides of the screen."] = "Не масштабировать карту мира до размеров экрана.";
L["ELVUI_DESC"] = "ElvUI это аддон для полной замены пользовательского интерфейса World of Warcraft."
L["Enable/Disable the loot frame."] = "Включить/выключить окно добычи ElvUI."
L["Enable/Disable the loot roll frame."] = "Включить/выключить фрейм распределения добычи ElvUI."
L["Exp/Rep Position"] = "Позиция опыта/репутации"
L["Fonts"] = "Шрифты"
L["Font Size"] = "Размер шрифта"
L["General"] = "Общие"
L["Hide Both"] = "Скрыть оба"
L["Left Only"] = "Только левый"
L['Location Text'] = "Текст локации"
L["Log Taints"] = "Отслеживать недочеты"
L["Login Message"] = "Сообщение загрузки"
L["LOGIN_MSG"] = "Добро пожаловать в %sElvUI|r версии %s%s|r, наберите /ec для доступа в меню настроек. Если Вам нужна техническая поддержка, посетите наш форум на www.tukui.org. Вы можете сообщать о багах и выдвигать предложения здесь - http://www.tukui.org/tickets/elvui/."
L["Loot"] = "Добыча"
L["Loot Roll"] = "Раздел добычи"
L["Main backdrop color of the UI."] = "Основной цвет фона интерфейса."
L["Main border color of the UI."] = "Основной цвет окантовок."
L['Map Alpha While Moving'] = "Прозрачность карты в движении"
L["Media"] = "Медиа"
L['Minimap Mouseover'] = "При наведении мыши"
L['Minimap Panels'] = "Информация у миникарты"
L["Minimap Size"] = "Размер миникарты"
L["Panel Backdrop"] = "Фон панелей"
L["Panel Height"] = "Высота панели"
L["Panel Texture (Left)"] = "Текстура левой панели"
L["Panel Texture (Right)"] = "Текстура правой панели"
L["Panel Width"] = "Ширина панели"
L["PANEL_DESC"] = "Регулирование размеров левой и правой панелей. Это окажет эффект на чат и сумки."
L["Primary Texture"] = "Основная текстура"
L["Reset all frames to their original positions."] = "Установить все фреймы на позиции по умолчанию"
L["Reset Anchors"] = "Сбросить позиции"
L["Right Only"] = "Только правый"
L["Secondary Texture"] = "Вторичная текстура"
L["Send ADDON_ACTION_BLOCKED errors to the Lua Error frame. These errors are less important in most cases and will not effect your game performance. Also a lot of these errors cannot be fixed. Please only report these errors if you notice a Defect in gameplay."] = "Отображать ошибки типа ADDON_ACTION_BLOCKED в фрейме ошибок lua. Эти ошибки в большинстве случаев не сильно важны и не влияют на производительность. Также многие из этих ошибок не могут быть исправлены. Пожалуйста, сообщайте об этих ошибках только если Вы заметите дефект в игре."
L["Set the font size for everything in UI. Note: This doesn't effect somethings that have their own seperate options (UnitFrame Font, Datatext Font, ect..)"] = "Установите размер шрифта для всего интерфейса. Это не действует на элементы с собственными настройками шрифтов (например, рамки юнитов)."
L["Show Both"] = "Показать оба"
L["Textures"] = "Текстуры"
L["The font that combat text will use. |cffFF0000WARNING: This requires a game restart or re-log for this change to take effect.|r"] = "Шрифт текста боя. |cffFF0000ВНИМАНИЕ: это действие потребует перезапуска игры или повторного входа в мир.|r"
L["The font that the core of the UI will use."] = "Шрифт для основного интерфейса."
L["The texture that will be used mainly for statusbars."] = "Эта текстура будет использоваться в основном для полос состояния."
L["This texture will get used on objects like chat windows and dropdown menus."] = "Эта текстура будет использоваться для таких объектов как окно чата и выпадающие меню."
L["Tiny Map"] = "Маленькая карта"
L["Toggle showing of the left and right chat panels."] = "Переключить отображение панелей чата."
L['Toggle Tutorials'] = "Показать помощь"
L["Top Screen"] = "Вверху экрана"
L["Value Color"] = "Цвет значений"
L["Welcome to ElvUI version %s!"] = "Добро пожаловать в ElvUI версии %s!"
L[ [=[Specify a filename located inside the World of Warcraft directory. Textures folder that you wish to have set as a panel background.

Please Note:
-The image size recommended is 256x128
-You must do a complete game restart after adding a file to the folder.
-The file type must be tga format.

Example: Interface\AddOns\ElvUI\media\textures\copy

Or for most users it would be easier to simply put a tga file into your WoW folder, then type the name of the file here.]=] ] = [=[Укажите имя файла в папке World of Warcraft, который Вы хотите использовать в качестве фона панелей.

Пожалуйста, учтите:
-Рекомендованный размер изображения 256x128
-Вы должны полностью перезапустить игру после добавления нового файла в папку.
-Тип файла должен быть tga.

Пример: Interface\AddOns\ElvUI\media\textures\copy

Для большинства пользователей будет легче просто положить tga файл в папку игры, а затем написать имя файла здесь.]=]

--Misc
L["Bars"] = "Полосы"
L["Can't Roll"] = "Не могу бросить кости"
L["Empty Slot"] = "Пустой слот"
L["Enable"] = "Включить"
L["Experience"] = "Опыт"
L["Filter already exists!"] = "Фильтр уже существует!" --Both UF and Nameplates
L["Filters"] = "Фильтры" --Both UF and Nameplates
L["Fishy Loot"] = "Улов"
L["Left Click:"] = "ЛКМ:"
L["Mouse Over"] = "При наведении" --Used by Bags and ABs
L["Raid Menu"] = "Рейдовое меню"
L["Remaining:"] = "Осталось:"
L["Rested:"] = "Бодрость:"
L["Right Click:"] = "ПКМ:"
L["Toggle Chat Frame"] = "Показать/скрыть чат" 
L["Toggle Embedded Addon"] = "Показать скрыть встроенный аддон"
L["XP:"] = "Опыт:"
L["You don't have enough money to repair."] = "У вас недостаточно денег для ремонта."
L["You don't have permission to mark targets."] = "У вас нет разрешения на установку меток"
L["Your items have been repaired for: "] = "Ваши предметы отремонтированы на: "
L["Your items have been repaired using guild bank funds for: "] = "Ваши предметы отремонтированы за счет гильдии на: "
L["Your version of ElvUI is out of date. You can download the latest version from www.tukui.org"] = "Ваша версия ElvUI устарела. Вы можете скачать последнюю версию на www.tukui.org"

--NamePlates
L["Add Name"] = "Добавить имя"
L["All"] = "Все"
L["Auras"] = "Ауры"
L["Bad Color"] = '"Плохой" цвет'
L["Bad Scale"] = '"Плохой" масштаб'
L["Bad Transition Color"] = 'Цвет "плохого" перехода'
L["Castbar Height"] = "Высота полосы заклинаний"
L['Color the border of the nameplate yellow when it reaches the threshold point on these types of frames.'] = "Окрашивать границу индикатора желтым, когда уровень здоровья достигает порогового значения на этих типах юнитов"
L['Color the border of the nameplate yellow when it reaches this point, it will be colored red when it reaches half this value.'] = "Окрашивать границу индикатора желтым, когда уровень здоровья достигает этого значения. Окраска сменится на красную при достижении половины этого значения."
L["Color the nameplate's healthbar by your current threat, Example: good threat color is used if your a tank when you have threat, opposite for DPS."] = 'Окрашивать индикатор, основываясь на текущем уровне угрозы. Например: "хороший" цвет используется, когда Вы танк с наивысшим уровнем угрозы, наоборот для дпс/лекаря.'
L["Combat Toggle"] = "Только в бою"
L["Controls the height of the nameplate"] = "Контролирует высоту индикатора"
L["Controls the height of the nameplate's castbar"] = "Контролирует высоту полосы заклинаний на индикаторе здоровья"
L["Controls the width of the nameplate"] = "Контролирует ширину индикатора"
L["Custom Color"] = "Свой цвет"
L["Custom Scale"] = "Свой масштаб"
L["Disable threat coloring for this plate and use the custom color."] = "Отключить цвет угрозы для этого индикатора и использовать установленный цвет."
L["Discipline"] = "Послушание"
L["Display a healer icon over known healers inside battlegrounds."] = "Отображать иконку над известными лекарями на полях боя."
L["Display level text on nameplate for nameplates that belong to units that aren't your level."] = "Отображать уровень на индикаторе, если уровень этого юнита отличен от Вашего."
L["Display your personal debuffs over the nameplate."] = "Отображение дебаффов, наложенных вами, над индикаторами."
L["Enemy"] = "Враг"
L["Enhance Threat"] = "Отображать угрозу"
L["Friendly NPC"] = "Дружественный НИП"
L["Friendly Player"] = "Дружественный игрок"

L['Low Health Threshold'] = "Пороговое значение здоровья"
L['Low Health Warning'] = "Предупреждение о низком здоровье"

L['Players'] = "Игроки"

--[[Reminders
L["Add Group"] = "Добавить группу"
L["Any"] = "Любая"
L["Attempted to show a reminder icon that does not have any spells. You must add a spell first."] = "Попытка отобразить напоминание, которое не содержит заклинаний. Сперва Вы должны добавить заклинание в список."
L["Caster"] = "Заклинатель"
L['CD Fade'] = "Прозрачность на восстановлении"
L["Change this if you want the Reminder module to check for weapon enchants, setting this will cause it to ignore any spells listed."] = "Измените этот пункт, если Вы хотите, чтобы фильтр отслеживал усиления оружия. Эта установка будет игнорировать любые перечисленные заклинания."
L["Combat"] = "В бою"
L["Cooldown"] = "Восстановление"
L["Disable Sound"] = "Отключить звук"
L["Don't play the warning sound."] = "Не проигрывать звук предупреждения"
L["Weapon"] = "Оружие"
]]

--Skins
L["Achievement Frame"] = "Достижения"
L['Alert Frames'] = "Предупреждения"
L["Archaeology Frame"] = "Археология"
L["Auction Frame"] = "Аукцион"
L["Barbershop Frame"] = "Парикмахерская"
L["BG Map"] = "Карта ПБ"
L["BG Score"] = "Таблица ПБ"
L["BN:"] = "BN:"
L["Calendar Frame"] = "Календарь"
L["Character Frame"] = "Окно персонажа"
L["Debug Tools"] = "Инструменты отладки"
L["Dressing Room"] = "Примерочная"
L["Embedded Addon"] = "Встроенный аддон"
L["Embedded Bar Height"] = "Высота полос"
L["Encounter Journal"] = "Атлас подземелий"

L["Loot Frames"] = "Добыча"
L['Mounts & Pets'] = "Транспорт и питомцы"

L["Pet Battle"] = "Битвы питомцев"
L['Spacing'] = "Расстояние"
L['The spacing in between bars.'] = "Расстояние между полосами"

--Static Popups
L["A setting you have changed will change an option for this character only. This setting that you have changed will be uneffected by changing user profiles. Changing this setting requires that you reload your User Interface."] = "Настройка, которую Вы только что изменили, будет влиять только на этого персонажа. Она не будет изменяться при смене профиля. Также это изменение требует перезагрузки интерфейса для вступления в силу."
L["Are you sure you want to delete all your gray items?"] = "Вы уверенны, что хотите удалить все предметы серого качества?"
L["Are you sure you want to disband the group?"] = "Вы уверены, что хотите распустить группу?"
L["Are you sure you want to reset every mover back to it's default position?"] = "Вы уверены, что хотите сбросить все фиксаторы на позиции по умолчанию?"
L["One or more of the changes you have made require a ReloadUI."] = true;

--Tooltip
L["Anchor"] = "Фиксатор"
L["Anchor Mode"] = "Режим прикрепления"
L["Combat Hide"] = "Скрыть в бою"
L["Count"] = "Кол-во"
L["Cursor"] = "Курсор"
L["Don't display the tooltip when mousing over a unitframe."] = "Не отображать подсказку при наведении курсора на рамки юнитов."


--Tutorials
L['Using the /farmmode <size> command will spawn a larger minimap on your screen that can be moved around, very useful when farming.'] = 'Использование команды /farmmode <размер> откроет миникарту большего размера, которую можно свободно перемещать по экрану. Очень полезно при фарме.';
L['You can use the /resetui command to reset all of your movers. You can also use the command to reset a specific mover, /resetui <mover name>.\nExample: /resetui Player Frame'] = 'Вы можете использовать команду /resetui чтобы сбросить положения всех фиксаторов. Вы также можете использовать команду /resetui <имя фиксатора> для сброса определенного фиксатора.\nПример: /resetui Player Frame';
L['For technical support visit us at www.tukui.org.'] = 'За технической поддержкой обращайтесь на www.tukui.org.';
L['You can toggle the microbar by using your middle mouse button on the minimap you can also accomplish this by holding shift and right clicking on the minimap.'] = 'Вы можете получить доступ к микроменю, кликнув средней кнопкой мыши на миникарте. Также можно кликнуть правой кнопкой при зажатой клавише shift.';
L['A raid marker feature is available by pressing Escape -> Keybinds scroll to the bottom under ElvUI and setting a keybind for the raid marker.'] = 'Функция рейдовых меток доступна в Escape -> Назначение клавиш. Прокрутите вниз до раздела ElvUI и назначьте клавишу для рейдовых меток.';
L['You can set your keybinds quickly by typing /kb.'] = "Вы можете быстро назначать клавиши, введя команду /kb.";
L['If you need to reset the gold datatext type /resetgold.'] = 'Если Вы хотите сбросить данные в инфо-тексте золота, введите команду /resetgold.';
L['The focus unit can be set by typing /focus when you are targetting the unit you want to focus. It is recommended you make a macro to do this.'] = 'Запомненную цель (фокус) можно установить командой /focus при взятии нужного врага в цель. Для этого рекомендуется сделать макрос.';
L['ElvUI has a dual spec feature which allows you to load different profiles based on your current spec on the fly. You can enable this from the profiles tab.'] = 'В ElvUI присутствует функция двойной специализации, которая позволит Вам использовать разные профили для разных наборов талантов. Вы можете включить эту функцию в разделе профилей.';
L['You can access copy chat and chat menu functions by mouse over the top right corner of chat panel and left/right click on the button that will appear.'] = 'Вы можете получить доступ к функциям копирования чата и меню чата, наведя курсор на верхний правый угол панели чата и кликнув левой/правой кнопкой мыши на появившейся кнопке.';
L['If you are experiencing issues with ElvUI try disabling all your addons except ElvUI, remember ElvUI is a full UI replacement addon, you cannot run two addons that do the same thing.'] = 'Если Вы испытываете проблемы с ElvUI, попробуйте отключить все аддоны, кроме самого ElvUI. Помните, ElvUI это аддон, полностью заменяющий интерфейс, Вы не можете одновременно использовать два аддона, выполняющих одинаковые функции.';
L['The buff panel to the right of minimap is a list of your consolidated buffs. You can disable it in Buffs and Debuffs options of ElvUI.'] = 'Панель с баффами справа от миникарты это список Ваших объединенных баффов. Вы можете отключить ее в разделе эффектов и аур в настройках ElvUI.';
L['If you accidently remove a chat frame you can always go the in-game configuration menu, press install, go to the chat portion and reset them.'] = 'Если Вы случайно удалили вкладку чата, всегда можно сделать следующее: зайти в конфигурацию, запустить установку, дойти до шага настроек чата и сбросить их.'
L['If your experience and reputation bars disappear, mouse over the place where they were and click them again.'] = 'Если Ваши полосы репутации и опыта пропали, наведите курсор на место, где они были, и кликните по ним снова.';
L['To setup which channels appear in which chat frame, right click the chat tab and go to settings.'] = 'Для настройки отображения каналов в чате кликните правой кнопкой мыши на закладке нужного чата и выберите пункт "параметры".';
L['To move abilities on the actionbars by default hold shift + drag. You can change the modifier key from the blizzard actionbar options menu.'] = 'Для перемещения способностей по панелям команд нужно перемещать их с зажатой клавишей shift. Вы можете поменять модификатор в опциях панелей команд Blizzard.';

--UnitFrames
L['Above'] = "Сверху"
L["Add a spell to the filter."] = "Добавить заклинание в фильтр"
L["Add Spell"] = "Добавить заклинание"
L["Add SpellID"] = "Добавить ID заклинания"
L['Allow displaying of aura bars that are considered consolidated by Blizzard.'] = "Скрыть полосы аур, которые отображаются в полосе объединенных баффов"
L['Allow displaying of aura bars that do not have a duration.'] = "Разрешить отображение полос для аур, не имеющих времени действия"
L["An Y offset (in pixels) to be used when anchoring new frames."] = "Отступ по оси Y (в пикселях) при добавлении новых рамок"
L["Any Unit"] = "Любой юнит"
L["Arena Frames"] = "Арена"
L["Assist Frames"] = "Помощники"
L["Attach To"] = "Прикрепить к"
L['Aura Bars'] = "Полосы аур"
L["Bad"] = "Плохое"
L["Bars will transition smoothly."] = "Полосы будут изменяться плавно"
L['Below'] = "Снизу"
L["Blacklist"] = "Черный список"
L["Blank"] = "Пусто"
L["Boss Frames"] = "Боссы"
L["Buff Indicator"] = "Индикатор баффов"
L["Buffs"] = "Баффы"
L["Camera Distance Scale"] = "Дистанция камеры"
L["Castbar"] = "Полоса заклинаний"
L["Class Backdrop"] = "Фон по классу"
L["Classbar"] = "Полоса класса"
L['Class Names'] = "Имена по классу"
L["Class Health"] = "Здоровье по классу"
L["Class Power"] = "Ресурс по классу"
L["Color"] = "Цвет"
L["Color health by ammount remaining."] = "Окрашивает полосу здоровья в зависимости от оставшегося его количества."
L["Color health by classcolor or reaction."] = "Окрашивает полосу здоровья по цвету класса или отношению."
L["Color Icons"] = "Окрашивать иконки"
L["Color power by classcolor or reaction."] = "Окрашивает полосу ресурсов по цвету класса или реакции."
L["Color the health backdrop by class or reaction."] = "Окрасить фон полосы здоровья по цвету класса или реакции."
L["Color the icon to their set color in the filters section, otherwise use the icon texture."] = "Окрашивает иконки в установленный в фильтре цвет. В противном случае использует текстуру иконки."
L['Color the name text by class or reaction.'] = "Окрашивает имена по цвету класса или отношению."
L["Color the unit healthbar if there is a debuff that can be dispelled by you."] = "Изменять цвет полосы здоровья, если на юните есть дебафф, который Вы можете снять."
L["Column Point"] = "Точка столбца"
L["Column Spacing"] = "Отступ столбцов"
L["Combat Fade"] = "Скрытие"
L["Combobar"] = "Полоса серии"
L["Copy From"] = "Скопировать из"
L["Create a filter, once created a filter can be set inside the buffs/debuffs section of each unit."] = "Создает фильтр. После создания он может быть установлен в секции баффов/дебаффов любого юнита."
L["Create Filter"] = "Создать фильтр"
L["Current"] = "Текущее"
L["Current - Max"] = "Текущее - Максимальное"
L["Current / Max"] = "Текущее / Максимальное"
L["Current - Percent"] = "Текущее - Процент"
L["Custom Health Backdrop"] = "Свой фон полосы здоровья"
L["Debuff Highlighting"] = "Подсветка дебаффов"
L["Debuffs"] = "Дебаффы"
L["Deficit"] = "Дефицит"
L["Delete a created filter, you cannot delete pre-existing filters, only custom ones."] = "Удалить созданный фильтр. Вы не можете удалять фильтры по умолчанию, только созданные вручную."
L["Delete Filter"] = "Удалить фильтр"
L["Direction the health bar moves when gaining/losing health."] = "Направление, в котором заполняется полоса при потере/восполнении здоровья."
L["Disable Blizzard"] = "Отключить фреймы Blizard"
L["Disables the blizzard party/raid frames."] = "Отключает фреймы группы/рейда от Blizzard."
L["Disconnected"] = "Не в сети"
L["Display a spark texture at the end of the castbar statusbar to help show the differance between castbar and backdrop."] = "Отображать свечение на краю полосы заклинаний для более четкого отделения ее от фона."
L['Display Frames'] = "Показать рамки"
L["Display Player"] = "Показывать себя"
L["Display Target"] = "Показывать цель"
L["Display the rested icon on the unitframe."] = "Отображать иконку отдыха на рамке игрока"
L["Display the target of the cast on the castbar."] = "Отображать имя цели заклинания на полосе."
L["Display tick marks on the castbar for channelled spells. This will adjust automatically for spells like Drain Soul and add additional ticks based on haste."] = "Отображать метки тиков на полосе заклинаний для поддерживаемых заклинаний. Они будут автоматически масштабироваться для заклинаний вроде Похищения души и добавлять новые тики, основываясь на показателе скорости."
L["Down"] = "Вниз"
L["Duration Limit"] = "Предел длительности"
L["Fade the unitframe when out of combat, not casting, no target exists."] = "Скрывать фрейм, когда Вы вне боя, не произносите заклинаний или отсутствует цель."
L["Fill"] = "Заполнение"
L["Filled"] = "По ширине рамки"
L["Filter Type"] = "Тип фильтра"
L["Focus Frame"] = "Фокус"
L["FocusTarget Frame"] = "Цель фокуса"
L["Format"] = "Формат"
L["Frame"] = "Рамка"
L["Frequent Updates"] = "Частое обновление"


--Unused O_o
L["Alt-Power"] = "Доп. Ресурс"
L['Anchor To'] = "Прикреплять к" --Possybly meant to be in aura bars section of unitframes




