-- 繁體中文版由 elmush 翻譯
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("ElvUI", "zhTW")
if not L then return end

--ActionBars 快捷列
L[" |cff00ff00bound to |r"] = " |cff00ff00綁定至 |r";
L["Action Paging"] = "快捷列切換";
L["ActionBars"] = "快捷列";
L["All keybindings cleared for |cff00ff00%s|r."] = "已清除 |cff00ff00%s|r 所有的快捷綁定。";
L["Anchor Point"] = "定位方向"; --also in unitframes
L["Backdrop"] = "背景";
L["Bar "] = "快捷列 ";
L["Binding"] = "綁定";
L["Binds Discarded"] = "已取消綁定";
L["Binds Saved"] = "已儲存綁定";
L["Button Size"] = "按鈕大小"; --Also used in Bags
L["Button Spacing"] = "按鈕間距"; --Also used in Bags
L["Buttons Per Row"] = "每行按鈕數";
L["Buttons"] = "按鈕數";
L["Color when the text is about to expire"] = "即將冷卻完畢的數字顏色";
L["Color when the text is in the days format."] = "冷卻時間以天計算時的文字顏色。";
L["Color when the text is in the hours format."] = "冷卻時間以小時計算時的文字顏色。";
L["Color when the text is in the minutes format."] = "冷卻時間以分計算時的文字顏色。";
L["Color when the text is in the seconds format."] = "冷卻時間以秒計算時的文字顏色。";
L["Cooldown Text"] = "冷卻文字";
L["Days"] = "天";
L["Discard"] = "取消";
L["Display bind names on action buttons."] = "在快捷列按鈕上顯示快捷鍵文字。";
L["Display cooldown text on anything with the cooldown spiril."] = "倒數計時，顯示所有冷卻時間。";
L["Display macro names on action buttons."] = "在快捷列按鈕上顯示巨集名稱。";
L["Expiring"] = "即將冷卻完畢";
L["Height Multiplier"] = "高度倍增";
L["Hours"] = "時";
L["Key"] = "鍵";
L["Keybind Mode"] = "快捷鍵綁定模式";
L["Keybind Text"] = "快捷鍵文字";
L["KEY_ALT"] = "A"
L["KEY_BUTTON3"] = "M3"
L["KEY_CTRL"] = "C"
L["KEY_DELETE"] = "Del"
L["KEY_HOME"] = "Hm"
L["KEY_INSERT"] = "Ins"
L["KEY_MOUSEBUTTON"] = "M"
L["KEY_MOUSEWHEELDOWN"] = "MwD"
L["KEY_MOUSEWHEELUP"] = "MwU"
L["KEY_NUMPAD"] = "N"
L["KEY_PAGEDOWN"] = "PD"
L["KEY_PAGEUP"] = "PU"
L["KEY_SHIFT"] = "S"
L["KEY_SPACE"] = "SpB"
L["LOCK_AB_ERROR"] = "It has come to our attention that you do not have your actionbars locked. This may cause abilities to be used while dragging buttons to differant slots. Please run the Set CVar portion of the Installation process (Step 2). This can be done by typing /ec and clicking the Install button."
L["Low Threshold"] = "冷卻時間低閥值";
L["Macro Text"] = "巨集名稱";
L['Max Paging'] = true;
L["Minutes"] = "分";
L["Mouse Over"] = "游標顯示"; --Also used in Bags
L["Multiply the backdrops height or width by this value. This is usefull if you wish to have more than one bar behind a backdrop."] = "背景框高度或寬度依此數值倍增，若想在背景框置放多列快捷列，此功能即可派上用場。";
L["No bindings set."] = "未設定快捷綁定。";
L["Pet Bar"] = "寵物快捷列";
L["Restore Bar"] = "還原快捷列";
L["Restore the actionbars default settings"] = "將此快捷列還原至預設設定";
L["Seconds"] = "秒";
L["Set the font size of the action buttons."] = "設訂快捷列按鈕的字體大小";
L["ShapeShift Bar"] = "姿態列";
L["The ammount of buttons to display per row."] = "每行按鈕顯示數量。";
L["The ammount of buttons to display."] = "快捷列按鈕顯示數量。";
L["The first button anchors itself to this point on the bar."] = "快捷列第一個按鈕的所在位置。";
L["The size of the action buttons."] = "快捷列按鈕大小。";
L["Threshold before text turns red and is in decimal form. Set to -1 for it to never turn red"] = "冷卻時間低於此秒數後，冷卻時間將變為紅色數字，並以小數顯示，設為 -1 時，冷卻時間將不會變為紅色";
L["Toggles the display of the actionbars backdrop."] = "顯示/隱藏快捷列背景框。";
L["Visibility State"] = "顯示/隱藏快捷列背景框。";
L['When enabled the main actionbar will use the maximum amount of pages available. This means if you have another actionbar disabled, the actionbar page will become available on the main actionbar. Having this disabled will limit the main actionbar to two pages.'] = true;
L["Width Multiplier"] = "寬度倍增";
L[ [=[This works like a macro, you can run different situations to get the actionbar to page differently.
 Example: '[combat] 2;']=] ] = [=[此功能與巨集概念類似，可根據不同情境，切換至不同的快捷列設置。
例如：'[combat] 2;']=]
L[ [=[This works like a macro, you can run different situations to get the actionbar to show/hide differently.
 Example: '[combat] show;hide']=] ] = [=[此功能與巨集概念類似，可根據不同情境，切換顯示/隱藏快捷列。
例如：'[combat] show;hide']=]

--Bags 背包
L["Ascending"] = "遞增排序";
L["Bag Columns"] = "銀行欄位欄數";
L["Bag-Bar"] = "背包欄";
L["Bags"] = "背包";
L["BAGS_DESC"] = "調整 ElvUI 的背包設定。";
L["Bank Columns"] = "背包欄數";
L["Bar Direction"] = "背包欄排序方向";
L["Bottom to Top"] = "由下至上";
L["Click to search.."] = "按一下以搜尋…";
L["copperabbrev"] = "|cffeda55fc|r" --Also used in gold datatext
L["Delete Grays"] = "刪除灰色物品";
L["Deleted %d gray items. Total Worth: %s"] = "已刪除灰色物品「%d」，總價值：%s";
L["Descending"] = "遞減排序";
L["Direction the bag sorting will use to allocate the items."] = "整理背包物品時，將依此排序方向排放物品。";
L["Enable Bag-Bar"] = "啟用背包欄";
L["Enable/Disable the all-in-one bag."] = "啟用/停用整合背包";
L["Enable/Disable the Bag-Bar."] = "啟用/停用背包欄。";
L["goldabbrev"] = "|cffffd700g|r" --Also used in gold datatext
L["Hold Shift:"] = "按住 Shift：";
L["No gray items to delete."] = "沒有可刪除的灰色物品。";
L["No gray items to sell."] = "沒有可出售的灰色物品。";
L["Number of columns (width) of bags. Set it to 0 to match the width of the chat panels."] = "背包欄數 (寬)，若設為 0，將與對話視窗等寬。";
L["Number of columns (width) of the bank. Set it to 0 to match the width of the chat panels."] = "銀行欄位欄數 (寬)，若設為 0，將與對話視窗等寬。";
L["Purchase"] = "購買銀行欄位";
L["Set the size of your bag buttons."] = "設定背包按鈕大小。";
L["silverabbrev"] = "|cffc7c7cfs|r" --Also used in gold datatext
L["Sort Bags"] = "整理背包";
L["Sort Direction"] = "整理排序方向"; --Also used in Buffs and Debuffs
L["Sort Orientation"] = "整理排序方向";
L["Sort Special"] = "整理特殊背包";
L["Stack Items"] = "堆疊物品";
L["Stack Special"] = "堆疊特殊背包";
L["The direction that the bag frames be (Horizontal or Vertical)."] = "背包框架排序方向 (水平或垂直)。";
L["The direction that the bag frames will grow from the anchor."] = "新增的背包框架將依此定位方向排序。";
L["The frame is not shown unless you mouse over the frame."] = "僅於游標移經快捷列時顯示其框架。";
L["The spacing between buttons."] = "兩個按鈕間的間距。";
L["Toggle Bags"] = "顯示/隱藏背包";
L["Top to Bottom"] = "由上至下";
L["Vendor Grays"] = "出售灰色物品";
L["Vendored gray items for:"] = "已售出灰色物品，共得：";
L["X Offset"] = "X 軸位移";
L["Y Offset"] = "Y 軸位移"; --Another variation in unitframes yOffset
L["You must be at a vendor."] = "你必須與商人對話。";

--Buffs and Debuffs (Needs translation)
L['AURAS_DESC'] = 'Configure the aura icons that appear near the minimap.';
L['Begin a new row or column after this many auras.'] = true;
L['Consolidated Buffs'] = true;
L['Defines how the group is sorted.'] = true;
L['Defines the sort order of the selected sort method.'] = true;
L['Display the consolidated buffs bar.'] = true;
L['Index'] = true;
L['Indicate whether buffs you cast yourself should be separated before or after.'] = true;
L['Limit the number of rows or columns.'] = true;
L['Max Wraps'] = true;
L['No Sorting'] = true;
L["Other's First"] = true;
L['Seperate'] = true;
L['Set the size of the individual auras.'] = true;
L['Sort Method'] = true;
L['Time'] = true;
L['Wrap After'] = true;
L['Your Auras First'] = true;

--Chat 對話視窗框架
L["AFK"] = "離開"; --Also used in datatexts and tooltip
L["Attempt to create URL links inside the chat."] = "對話視窗中若出現網址，建立連結。";
L["BG"] = "戰場";
L["BGL"] = "戰場隊長";
L["BN:"] = "戰網：";
L["Chat"] = "聊天";
L["CHAT_DESC"] = '聊天框架設定';
L["Copy Text"] = "複製文字";
L["Display the hyperlink tooltip while hovering over a hyperlink."] = "游標移經超連結時顯示提示資訊。";
L['DND'] = "忙碌";
L["Font Outline"] = "字體描邊"; --Also used in UnitFrames section
L["Font"] = true;
L["G"] = "公會";
L["Hyperlink Hover"] = "超連結提示資訊";
L["Keyword Alert"] = true;
L['Keywords'] = true;
L['List of words to color in chat if found in a message. If you wish to add multiple words you must seperate the word with a comma. To search for your current name you can use %MYNAME%.\n\nExample:\n%MYNAME%, ElvUI, RBGs, Tank'] = true;
L["Number of time in seconds to scroll down to the bottom of the chat window if you are not scrolled down completely."] = "不直接將移至對話框最底端時，捲動至最底端所需的秒數。";
L["O"] = "幹部";
L["P"] = "隊伍";
L["PG"] = "隊員";
L["PL"] = "隊長";
L["Prevent the same messages from displaying in chat more than once within this set amount of seconds, set to zero to disable."] = "設定秒數，在此設定秒數內，相同的訊息僅會在對話視窗中顯示一次，設為 0 即可停用此功能。";
L["R"] = "團隊";
L["RL"] = "團隊隊長";
L["RW"] = "團隊警告";
L['says'] = "說";
L["Scroll Interval"] = "捲動間隔";
L["Set the font outline."] = "字體描邊設定。"; --Also used in UnitFrames section
L["Short Channels"] = "隱藏頻道名稱";
L["Shorten the channel names in chat."] = "在對話視窗中隱藏頻道名稱。";
L["Spam Interval"] = "洗頻訊息間隔";
L["Sticky Chat"] = "記憶對話頻道";
L['Trade'] = "拾取交易";
L["URL Links"] = "網址連結";
L["When opening the Chat Editbox to type a message having this option set means it will retain the last channel you spoke in. If this option is turned off opening the Chat Editbox should always default to the SAY channel."] = "若設定此選項，當你開啟「對話編輯方塊」，在其內輸入訊息時，系統會記憶最後發言的頻道。若關閉此選項，開啟「對話編輯方塊」後，將一律使用預設「說」(/說) 頻道。";
L["Whisper Alert"] = true;
L['whispers'] = "悄悄話";
L['yells'] = "大喊";
L[ [=[Specify a filename located inside the World of Warcraft directory. Textures folder that you wish to have set as a panel background.

Please Note:
-The image size recommended is 256x128
-You must do a complete game restart after adding a file to the folder.
-The file type must be tga format.

Example: Interface\AddOns\ElvUI\media\textures\copy

Or for most users it would be easier to simply put a tga file into your WoW folder, then type the name of the file here.]=] ] = [=[若要設定對話框背景，請將你希望設定為背景的檔案置放於 WoW 目錄底下的「Textures」資料夾中，並於下欄指定該檔名。

請注意：
- 影像尺寸建議為 256 x 128
- 在此資料夾新增檔案後，請務必重新啟動遊戲。
- 檔案必須為 tga 格式。

範例：Interface\AddOns\ElvUI\media\textures\copy

對多數玩家來說，較簡易的方式是將 tga 檔放入 WoW 資料夾中，然後在此處輸入檔案名稱。]=];

--Config / Install | 設定 / 安裝設定
L['Bar'] = true;
L["Caster DPS"] = "遠程輸出";
L["Chat Set"] = "聊天設定完畢";
L['Choose a theme layout you wish to use for your initial setup.'] = true;
L['Classic'] = true;
L["Click the button below to resize your chat frames, unitframes, and reposition your actionbars."] = "按一下下方按鈕，重新調整對話視窗、單位框架的大小，並調整快捷列的位置。";
L['Config Mode:'] = true;
L["CVars Set"] = "參數設定完畢";
L["CVars"] = "參數";
L["ElvUI Installation"] = "安裝 ElvUI";
L["Finished"] = "設定完畢";
L["Grid Size:"] = "Grid 尺寸：";
L["Healer"] = "補師";
L["High Resolution"] = true;
L["high"] = "高";
L["Importance: |cff07D400High|r"] = "重要性：|cff07D400高|r";
L["Importance: |cffD3CF00Medium|r"] = "重要性：|cffD3CF00中|r";
L["Importance: |cffFF0000Low|r"] = "重要性：|cffFF0000低|r";
L["Install"] = "安裝";
L["Installation Complete"] = "安裝完畢";
L["Layout Set"] = "版面配置設定";
L["Layout"] = "版面配置";
L["Lock"] = "鎖定";
L['Low Resolution'] = true;
L["low"] = "低";
L["Movers unlocked. Move them now and click Lock when you are done."] = "移動框架已解除鎖定。請移動其位置，移動完畢時請按一下「鎖定」。";
L["Physical DPS"] = "物理輸出";
L["Please click the button below so you can setup variables and ReloadUI."] = "請按下方按鈕設定變數並重載介面。";
L["Please click the button below to setup your CVars."] = "請按下方按鈕以設定參數。";
L["Please press the continue button to go onto the next step."] = "請按「繼續」按鈕，執行下一個步驟。";
L["Resolution Style Set"] = "解析度樣式設定";
L["Resolution"] = "解析度";
L["Run the installation process."] = "執行安裝程序。";
L["Setup Chat"] = "設定對話視窗";
L["Setup CVars"] = "設定參數";
L["Skip Process"] = "略過程序";
L["Sticky Frames"] = "框架依附";
L["Tank"] = "坦克";
L["The chat windows function the same as Blizzard standard chat windows, you can right click the tabs and drag them around, rename, etc. Please click the button below to setup your chat windows."] = "對話視窗與 WoW 原始對話視窗的操作方式相同，你可以拖拉、移動分頁或重新命名分頁。請按下方按鈕以設定對話視窗。";
L["The in-game configuration menu can be accesses by typing the /ec command or by clicking the 'C' button on the minimap. Press the button below if you wish to skip the installation process."] = "若要進入內建設定選單，請輸入 /ec 指令，\n或者按一下小地圖旁的 C 按鈕。\n若要略過安裝程序，請按下方按鈕。";
L['Theme Set'] = true;
L['Theme Setup'] = true;
L["This install process will help you learn some of the features in ElvUI has to offer and also prepare your user interface for usage."] = "此安裝程序有助你瞭解 ElvUI 部份功能，並可協助你預先設定 UI。";
L["This is completely optional."] = "此為選擇性功能。";
L["This part of the installation process sets up your chat windows names, positions and colors."] = "此安裝步驟將會設定對話視窗的名稱、位置和顏色。";
L["This part of the installation process sets up your World of Warcraft default options it is recommended you should do this step for everything to behave properly."] = "此安裝步驟將會設定 WoW 預設選項，建議你執行此步驟，以確保功能均可正常運作。";
L["This resolution doesn't require that you change settings for the UI to fit on your screen."] = "若使用此解析度，無需另行變更 UI 設定，介面即已符合螢幕尺寸。";
L["This resolution requires that you change some settings to get everything to fit on your screen."] = "若使用此解析度，需另行變更 UI 設定，使介面元件符合螢幕尺寸。";
L["This will change the layout of your unitframes, raidframes, and datatexts."] = "此設定將變更單位框架、團隊框架、資訊文字等的版面配置。";
L["Toggle Anchors"] = "解鎖元件定位";
L['Toggle Configuration'] = true;
L["Unlock various elements of the UI to be repositioned."] = "解鎖介面上的各種元件，以移動其位置。";
L["Using the healer layout it is highly recommended you download the addon Clique to work side by side with ElvUI."] = "若你是補職，並使用補職版面配置，強烈建議你下載 Clique，與 ElvUI 搭配使用。";
L["Version"] = "版本";
L["You are now finished with the installation process. Bonus Hint: If you wish to access blizzard micro menu, middle click on the minimap. If you don't have a middle click button then hold down shift and right click the minimap. If you are in need of technical support please visit us at www.tukui.org."] = "已完成安裝程序。小提示：若想開啟微型選單，請在小地圖上按滑鼠中鍵。\n若滑鼠沒有中鍵按鈕，請按住 Shift 鍵，並在小地圖上按滑鼠右鍵。\n如需技術支援請至 www.tukui.org。";
L['You can always change fonts and colors of any element of elvui from the in-game configuration.'] = true;
L["You can now choose what layout you wish to use based on your combat role."] = "你可以依據角色定位，選擇希望使用的版面配置。";
L["You may need to further alter these settings depending how low you resolution is."] = "你必須依據解析度值，進一步調整這些設定。";
L["Your current resolution is %s, this is considered a %s resolution."] = "你目前的解析度為 %s，系統判定為 %s 解析度。";

--Credits 特別感謝
L["Coding:"] = "編碼：";
L["Credits"] = "特別感謝";
L["Donations:"] = "捐款：";
L["ELVUI_CREDITS"] = "我想透過這個特別方式，向那些協助測試、編碼及透過捐款協助過我的人表達感謝，請曾提供協助的朋友至論壇傳私訊給我，我會將你的名字添加至此處。";
L["Testing:"] = "測試：";

--DataTexts 資料文字
L["(Hold Shift) Memory Usage"] = "(按住 Shift) 記憶體使用量";
L["24-Hour Time"] = "24 小時制";
L["AP"] = "攻擊強度";
L["AVD: "] = "免傷：";
L["Avoidance Breakdown"] = "免傷統計";
L["Bandwidth"] = "頻寬";
L['Bases Assaulted'] = true;
L['Bases Defended'] = true;
L['Battleground datatexts temporarily hidden, to show type /bgstats or right click the "C" icon near the minimap.'] = true;
L['Battleground datatexts will now show again if you are inside a battleground.'] = true;
L['Battleground Texts'] = true;
L["Character: "] = "角色：";
L["Chest"] = "胸";
L["DataTexts"] = "資訊文字";
L["DATATEXT_DESC"] = "設定螢幕所顯示的部份資訊文字。";
L["Deficit:"] = "赤字：";
L['Demolishers Destroyed'] = true;
L["DPS"] = "傷害輸出";
L["Earned:"] = "賺取：";
L["Feet"] = "腳";
L['Flags Captured'] = true;
L['Flags Returned'] = true;
L["Friends List"] = "好友列表";
L['Gates Destroyed'] = true;
L['Graveyards Assaulted'] = true;
L['Graveyards Defended'] = true;
L["Hands"] = "手";
L["Head"] = "頭";
L["Hit"] = "命中";
L["Home Latency:"] = "本機延遲:";
L["HP"] = "生命值";
L["HPS"] = "治療輸出";
L["If not set to true then the server time will be displayed instead."] = "若關閉此選項，將顯示為伺服器時間。";
L["left"] = '左';
L["LeftChatDataPanel"] = '左聊天框';
L["LeftMiniPanel"] = '小地圖左側';
L["Legs"] = "腿";
L["Local Time"] = "本地時間";
L["lvl"] = "等級";
L["Main Hand"] = "主手";
L["middle"] = '中';
L['Mitigation By Level: '] = "等級減傷：";
L["Offhand"] = "副手";
L["Panels"] = "對話視窗";
L["Profit:"] = "利潤：";
L["right"] = '右';
L["RightChatDataPanel"] = '右聊天框';
L["RightMiniPanel"] = '小地圖右側';
L["Saved Raid(s)"] = "已有進度的副本";
L["Server: "] = "伺服器：";
L["Session:"] = "本次登入";
L["Shoulder"] = "肩";
L['Show BG Texts'] = true;
L["SP"] = "法術能量";
L["Spent:"] = "花費：";
L['Stats For:'] = true;
L["Toggle 24-hour mode for the time datatext."] = "資訊文字時間切換為 24 小時制。";
L["Total CPU:"] = "總 CPU：";
L["Total Memory:"] = "總記憶體:";
L["Total: "] = "合計：";
L['Towers Assaulted'] = true;
L['Towers Defended'] = true;
L["Unhittable:"] = "未命中：";
L["Waist"] = "腰";
L['When inside a battleground display personal scoreboard information on the main datatext bars.'] = true;
L["Wrist"] = "腕";

--DebugTools
L["%s: %s tried to call the protected function '%s'."] = "%s：%s 已嘗試呼叫受保護的「%s」功能。";
L["INCOMPATIBLE_ADDON"] = "插件 %s 不相容於 ElvUI 的 %s 模組。請停用不相容的插件，或停用模組。";
L["No locals to dump"] = "無可供傾印的本機資料";
L['|cFFE30000Lua error recieved. You can view the error message when you exit combat.'] = "|cFFE30000收到 LUA 錯誤報告，你可以在脫離戰鬥時檢視錯誤訊息。";

--General 一般
L["Accept Invites"] = "接受組隊邀請";
L['Adjust the size of the minimap.'] = "調整小地圖尺寸。";
L['Always Display'] = true;
L["Announce Interrupts"] = "斷法通知";
L["Announce when you interrupt a spell to the specified chat channel."] = "斷法時在指定頻道傳送通知訊息。";
L["Auto Repair"] = "自動修裝";
L["Auto Scale"] = "自動縮放";
L["Automatically accept invites from guild/friends."] = "自動接受公會成員/朋友的組隊邀請。";
L["Automatically repair using the following method when visiting a merchant."] = "與商人對話時，透過下列方式自動修復裝備。";
L["Automatically scale the User Interface based on your screen resolution"] = "依螢幕解析度自動縮放 UI 介面";
L["Automatically vendor gray items when visiting a vendor."] = "造訪商店時自動出售灰色物品。";
L['Change settings for the display of the location text that is on the minimap.'] = true;
L["Chat Bubbles"] = "對話泡泡";
L["Controls what the transparency of the worldmap will be set to when you are moving."] = "角色移動時，世界地圖的透明度。";
L["Disband Group"] = "解散隊伍";
L['Display emotion icons in chat.'] = true;
L['Display minimap panels below the minimap, used for datatexts.'] = true;
L["Don't scale the large world map to block out sides of the screen."] = true;
L["ELVUI_DESC"] = "ElvUI 為一套功能完整，可用來替換 WoW 原始介面的 UI 套件。";
L['Emotion Icons'] = true;
L["Enable/Disable the loot frame."] = "啟用/停用拾取框架";
L["Enable/Disable the loot roll frame."] = "啟用/停用擲骰框架。";
L['Enable/Disable the minimap. |cffFF0000Warning: This will prevent you from seeing the consolidated buffs bar, and prevent you from seeing the minimap datatexts.|r'] = true;
L["General"] = "一般設定";
L["Hide Both"] = "全部隱藏";
L["Left Only"] = "僅顯示左框背景";
L['Location Text'] = true;
L["Log Taints"] = true;
L["Login Message"] = "登入訊息";
L["LOGIN_MSG"] = '歡迎使用 %sElvUI|r %s%s|r 版，請輸入 /ec 進入設定介面。如需技術支援，請至 www.tukui.org。若想回報錯誤、提供建議，請至 http://www.tukui.org/tickets/elvui/。';
L["Loot Roll"] = "骰裝";
L["Loot"] = "拾取";
L["Map Alpha While Moving"] = true;
L["Media"] = "材質";
L['Minimap Mouseover'] = true;
L['Minimap Panels'] = true;
L["Panel Backdrop"] = "對話框背景";
L["Panel Height"] = "對話框高度";
L["Panel Texture (Left)"] = "對話框材質 (左)";
L["Panel Texture (Right)"] = "對話框材質 (右)";
L["Panel Width"] = "對話框寬度";
L["PANEL_DESC"] = '調整左、右對話框的大小，此設定將會影響對話與背包框架的大小。';
L["Reset all frames to their original positions."] = "將所有框架重設至原始位置。";
L["Reset Anchors"] = "重設位置";
L["Right Only"] = "僅顯示右框背景";
L["Send ADDON_ACTION_BLOCKED errors to the Lua Error frame. These errors are less important in most cases and will not effect your game performance. Also a lot of these errors cannot be fixed. Please only report these errors if you notice a Defect in gameplay."] = true;
L["Show Both"] = "全部顯示";
L["Tiny Map"] = true;
L["Toggle showing of the left and right chat panels."] = "顯示/隱藏左、右對話框背景。";
L['Toggle Tutorials'] = true;
L["Welcome to ElvUI version %s!"] = "歡迎使用 ElvUI %s 版！";

--Media
L["Backdrop color of transparent frames"] = "透明框架的背景顏色";
L["Backdrop Color"] = "背景顏色";
L["Backdrop Faded Color"] = "透明框架背景色";
L["Border Color"] = "邊框顏色";
L["Color some texts use."] = "部份文字所使用的顏色。";
L["Colors"] = "顏色"; --Also used in UnitFrames
L["CombatText Font"] = "戰鬥文字字體";
L["Default Font"] = "預設字體";
L["Font Size"] = "字體大小"; --Also used in UnitFrames
L["Fonts"] = "字體";
L["Main backdrop color of the UI."] = "介面背景主色";
L["Main border color of the UI."] = "介面邊框主色";
L["Primary Texture"] = "主要材質";
L["Secondary Texture"] = "次要材質";
L["Set the font size for everything in UI. Note: This doesn't effect somethings that have their own seperate options (UnitFrame Font, Datatext Font, ect..)"] = "設定介面上所有字體的大小，但不包含本身有獨立設定的字體 (如單位框架字體、資訊文字字體等…)";
L["Textures"] = "材質";
L["The font that combat text will use. |cffFF0000WARNING: This requires a game restart or re-log for this change to take effect.|r"] = "戰鬥文字所使用的字體。|cffFF0000警告：需重啟遊戲或重新登入才可使此變更生效。|r";
L["The font that the core of the UI will use."] = "核心 UI 所使用的字體。";
L["The texture that will be used mainly for statusbars."] = "此材質主用於狀態列上。";
L["This texture will get used on objects like chat windows and dropdown menus."] = "此材質適用於對話框、下拉式選單等物件上。";
L["Value Color"] = "數值顏色";

--Misc 其他
L["Can't Roll"] = "無法需求此裝備";
L["Empty Slot"] = "空白欄位";
L["Enable"] = "啟用"; --Doesn't fit a section since it's used a lot of places
L["Experience"] = "經驗/聲望條";
L["Fishy Loot"] = "貪婪";
L["Left Click:"] = "點按左鍵："; --layout\layout.lua
L["Raid Menu"] = "團隊選單";
L["Remaining:"] = "剩餘：";
L["Rested:"] = "充分休息：";
L["Right Click:"] = "點按右鍵："; --layout\layout.lua
L["Toggle Chat Frame"] = "顯示/隱藏對話框架"; --layout\layout.lua
L["XP:"] = "經驗：";
L["You don't have enough money to repair."] = "資金不足，無法修復裝備。";
L["You don't have permission to mark targets."] = "你沒有標記目標的權限。";
L["Your items have been repaired for: "] = "已修復裝備，共支出：";
L["Your items have been repaired using guild bank funds for: "] = "已使用公會資金修復裝備，共支出：";
L["Your version of ElvUI is out of date. You can download the latest version from http://www.tukui.org"] = "ElvUI 版本已過期，請至 http://www.tukui.org 下載最新版"; --core\core.lua

--NamePlates
L["Add Name"] = "新增名稱";
L["All"] = "所有人";
L["Auras"] = "光環";
L["Bad Color"] = "仇恨異常色";
L["Bad Scale"] = "仇恨異常比例";
L["Bad Transition Color"] = "仇恨異常轉換色";
L["Castbar Height"] = "施法條高度";
L['Color the border of the nameplate yellow when it reaches the threshold point on these types of frames.'] = true;
L['Color the border of the nameplate yellow when it reaches this point, it will be colored red when it reaches half this value.'] = true;
L["Color the nameplate's healthbar by your current threat, Example: good threat color is used if your a tank when you have threat, opposite for DPS."] = "依據目前仇恨狀況改變血條的顏色，如坦職為仇恨目標，則顯示仇恨正常色，輸出職則相反。";
L["Combat Toggle"] = "戰鬥顯示";
L["Controls the height of the nameplate"] = "血條的高度設定";
L["Controls the height of the nameplate's castbar"] = "控制血條的施法條高度";
L["Controls the width of the nameplate"] = "血條的寬度設定";
L["Custom Color"] = "自訂顏色";
L["Custom Scale"] = "自訂比例";
L["Disable threat coloring for this plate and use the custom color."] = "此血條停用仇恨顏色，並使用自訂顏色。";
L["Discipline"] = "戒律";
L["Display a healer icon over known healers inside battlegrounds."] = "戰場隊伍中，為確認為補職的玩家標上補職圖示。";
L["Display level text on nameplate for nameplates that belong to units that aren't your level."] = "若單位目標等級不同於己，在血條上顯示其等級。";
L["Display your personal debuffs over the nameplate."] = "在目標血條上顯示自己施放的減益光環。";
L["Enemy"] = "敵對";
L["Enhance Threat"] = "仇恨強化顯示";
L["Filter already exists!"] = "已存在篩選器！";
L["Filters"] = "篩選器"; --Also used in UnitFrames
L["Friendly NPC"] = "友好 NPC";
L["Friendly Player"] = "友好玩家";
L["Good Color"] = "仇恨正常色";
L["Good Scale"] = "仇恨正常比例";
L["Good Transition Color"] = "仇恨正常轉換色";
L["Healer Icon"] = "補職圖示";
L["Hide"] = "隱藏";
L["Holy"] = "神聖";
L['Low Health Threshold'] = true;
L['Low Health Warning'] = true;
L["NamePlates"] = "血條";
L["NAMEPLATE_DESC"] = "修改血條設定。";
L["Personal Debuffs"] = "己方減益光環";
L['Players'] = true;
L["Prevent any nameplate with this unit name from showing."] = "若血條含有此單位名稱，則不予顯示。";
L["Remove Name"] = "移除名稱";
L["Restoration"] = "恢復";
L["Select a filter to use. These are imported from the unitframe aura filter."] = "此由單位框架光環篩選器所匯入，選擇欲使用的篩選器。"; --This one is not visible in the GUI since desc is not used on select groups. Keep for dropdown based menus?
L["Set the scale of the nameplate."] = "設定血條的比例。";
L["This color is displayed when gaining/losing threat, for a tank it would be displayed when gaining threat, for a dps/healer it would be displayed when losing threat"] = "坦職將成為仇恨目標，或輸出/補職將成為非仇恨目標時所顯示的顏色";
L["This color is displayed when gaining/losing threat, for a tank it would be displayed when losing threat, for a dps/healer it would be displayed when gaining threat"] = "坦職將成為非仇恨目標，或輸出/補職將成為仇恨目標時所顯示的顏色";
L["This is displayed when you don't have threat as a tank, if you do have threat it is displayed as a DPS/Healer"] = "坦職非仇恨目標，或輸出/補職為仇恨目標時所顯示的顏色";
L["This is displayed when you have threat as a tank, if you don't have threat it is displayed as a DPS/Healer"] = "坦職為仇恨目標，或輸出/補職非仇恨目標時所顯示的顏色";
L["Threat"] = "仇恨";
L["Toggles the nameplates off when not in combat."] = "脫離戰鬥時，自動隱藏血條。";
L["Use this filter."] = "使用此篩選器。";
L["You can't remove a default name from the filter, disabling the name."] = "你無法自篩選器移除或停用預設名稱。";

--Skins
L["Achievement Frame"] = true;
L['Alert Frames'] = true;
L["Archaeology Frame"] = true;
L["Auction Frame"] = true;
L["Barbershop Frame"] = true;
L["BG Map"] = true;
L["BG Score"] = true;
L["Calendar Frame"] = true;
L["Character Frame"] = true;
L["Debug Tools"] = true;
L["Dressing Room"] = true;
L["Embedded Addon"] = true;
L["Embedded Bar Height"] = true;
L["Encounter Journal"] = true;
L["Friends"] = true;
L["Glyph Frame"] = true;
L["Gossip Frame"] = true;
L["Greeting Frame"] = true;
L["Guild Bank"] = true;
L["Guild Control Frame"] = true;
L["Guild Frame"] = true;
L["Guild Registrar"] = true;
L["Help Frame"] = true;
L["Inspect Frame"] = true;
L["KeyBinding Frame"] = true;
L["LF Guild Frame"] = true;
L["LFG Frame"] = true;
L["Loot Frames"] = true;
L["Macro Frame"] = true;
L["Mail Frame"] = true;
L["Merchant Frame"] = true;
L["Misc Frames"] = true;
L["Mounts & Pets"] = true;
L["Non-Raid Frame"] = true;
L["Pet Battle"] = true;
L["Pet Frame"] = true;
L["Petition Frame"] = true;
L["PvP Frames"] = true;
L["Quest Frames"] = true;
L["Raid Frame"] = true;
L["Reforge Frame"] = true;
L["Select an addon to embed to the right chat window. This will resize the addon to fit perfectly into the chat window, it will also parent it to the chat window so hiding the chat window will also hide the addon."] = true;
L["Skin the blizzard chat bubbles."] = true;
L["Skins"] = true;
L["SKINS_DESC"] = "Adjust Skin settings."
L["Socket Frame"] = true;
L['Spacing'] = true;
L["Spellbook"] = true;
L["Stable"] = true;
L["Tabard Frame"] = true;
L["Talent Frame"] = true;
L["Taxi Frame"] = true;
L["The height of the bars while skada is embedded."] = true;
L['The spacing in between bars.'] = true;
L["Time Manager"] = true;
L["TOGGLESKIN_DESC"] = "Enable/Disable this skin."
L["Trade Frame"] = true;
L["TradeSkill Frame"] = true;
L["Trainer Frame"] = true;
L["World Map"] = true;

--Static Popups
L["A setting you have changed will change an option for this character only. This setting that you have changed will be uneffected by changing user profiles. Changing this setting requires that you reload your User Interface."] = true;
L["Are you sure you want to delete all your gray items?"] = true;
L["Are you sure you want to disband the group?"] = true;
L["Are you sure you want to reset every mover back to it's default position?"] = true;
L["Can't buy anymore slots!"] = true;
L["Hover your mouse over any actionbutton or spellbook button to bind it. Press the escape key or right click to clear the current actionbutton's keybinding."] = true;
L["One or more of the changes you have made require a ReloadUI."] = true;
L["One or more of the changes you have made will effect all characters using this addon. You will have to reload the user interface to see the changes you have made."] = true;
L["Save"] = true;
L["You have changed your UIScale, however you still have the AutoScale option enabled in ElvUI. Press accept if you would like to disable the Auto Scale option."] = true;
L["You must purchase a bank slot first!"] = true;

--Tooltip
L["Anchor Mode"] = true;
L["Anchor"] = true;
L["Combat Hide"] = true;
L["Count"] = true;
L["Cursor"] = true;
L["Don't display the tooltip when mousing over a unitframe."] = true;
L["Hide tooltip while in combat."] = true;
L["Set the type of anchor mode the tooltip should use."] = true;
L["Smart"] = true;
L["Targeted By:"] = true;
L["Tooltip"] = true;
L["TOOLTIP_DESC"] = "Setup options for the Tooltip."
L["UF Hide"] = true;
L["When in a raid group display if anyone in your raid is targetting the current tooltip unit."] = true;
L["Who's targetting who?"] = true;

--Tutorials
L['A raid marker feature is available by pressing Escape -> Keybinds scroll to the bottom under ElvUI and setting a keybind for the raid marker.'] = true;
L['ElvUI has a dual spec feature which allows you to load different profiles based on your current spec on the fly. You can enable this from the profiles tab.'] = true;
L['For technical support visit us at http://www.tukui.org.'] = true;
L['If you accidently remove a chat frame you can always go the in-game configuration menu, press install, go to the chat portion and reset them.'] = true
L['If you are experiencing issues with ElvUI try disabling all your addons except ElvUI, remember ElvUI is a full UI replacement addon, you cannot run two addons that do the same thing.'] = true;
L['If you need to reset the gold datatext type /resetgold.'] = true;
L['If your experience and reputation bars disappear, mouse over the place where they were and click them again.'] = true;
L['The buff panel to the right of minimap is a list of your consolidated buffs. You can disable it in Buffs and Debuffs options of ElvUI.'] = true;
L['The focus unit can be set by typing /focus when you are targetting the unit you want to focus. It is recommended you make a macro to do this.'] = true;
L['To move abilities on the actionbars by default hold shift + drag. You can change the modifier key from the blizzard actionbar options menu.'] = true;
L['To setup which channels appear in which chat frame, right click the chat tab and go to settings.'] = true;
L['Using the /farmmode <size> command will spawn a larger minimap on your screen that can be moved around, very useful when farming.'] = true;
L['You can access copy chat and chat menu functions by mouse over the top right corner of chat panel and left/right click on the button that will appear.'] = true;
L['You can set your keybinds quickly by typing /kb.'] = true;
L['You can toggle the microbar by using your middle mouse button on the minimap you can also accomplish this by holding shift and right clicking on the minimap.'] = true;
L['You can use the /resetui command to reset all of your movers. You can also use the command to reset a specific mover, /resetui <mover name>.\nExample: /resetui Player Frame'] = true;

--UnitFrames
L["%s frame(s) has a conflicting anchor point, please change either the buff or debuff anchor point so they are not attached to each other. Forcing the debuffs to be attached to the main unitframe until fixed."] = true;
L['Above'] = true;
L["Add a spell to the filter."] = true;
L["Add Spell"] = true;
L["Add SpellID"] = true;
L['Allow displaying of auras that are considered consolidated by Blizzard.'] = true;
L['Allow displaying of auras that do not have a duration.'] = true;
L["An X offset (in pixels) to be used when anchoring new frames."] = true;
L["An Y offset (in pixels) to be used when anchoring new frames."] = true;
L["Any Unit"] = true;
L["Arena Frames"] = true;
L["Assist Frames"] = true;
L["Attach To"] = true;
L['Aura Bars'] = true;
L["Bad"] = true;
L["Bars will transition smoothly."] = true;
L['Bars'] = true; --Also used in ExpRepBar tooltip
L['Below'] = true;
L["Blacklist"] = true;
L["Blank"] = true;
L["Boss Frames"] = true;
L["Buff Indicator"] = true;
L["Buffs"] = true;
L["Camera Distance Scale"] = true;
L["Castbar"] = true;
L["Class Backdrop"] = true;
L["Class Health"] = true;
L['Class Names'] = true;
L["Class Power"] = true;
L["Classbar"] = true;
L["Color health by ammount remaining."] = true;
L["Color health by classcolor or reaction."] = true;
L["Color Icons"] = true;
L["Color power by classcolor or reaction."] = true;
L["Color the health backdrop by class or reaction."] = true;
L["Color the icon to their set color in the filters section, otherwise use the icon texture."] = true;
L['Color the name text by class or reaction.'] = true;
L["Color the unit healthbar if there is a debuff that can be dispelled by you."] = true;
L["Color"] = true;
L["Column Point"] = true;
L["Column Spacing"] = true;
L["Combat Fade"] = true;
L["Combobar"] = true;
L["Copy From"] = true;
L["Create a filter, once created a filter can be set inside the buffs/debuffs section of each unit."] = true;
L["Create Filter"] = true;
L["Current - Max"] = true;
L["Current - Percent"] = true;
L["Current / Max"] = true;
L["Current"] = true;
L["Custom Health Backdrop"] = true;
L["Debuff Highlighting"] = true;
L["Debuffs"] = true;
L["Deficit"] = true;
L["Delete a created filter, you cannot delete pre-existing filters, only custom ones."] = true;
L["Delete Filter"] = true;
L["Direction the health bar moves when gaining/losing health."] = true;
L["Disable Blizzard"] = true;
L['Disabled'] = true;
L["Disables the blizzard party/raid frames."] = true;
L["Disconnected"] = true;
L["Display a spark texture at the end of the castbar statusbar to help show the differance between castbar and backdrop."] = true;
L['Display Frames'] = true;
L["Display Player"] = true;
L["Display Target"] = true;
L["Display the rested icon on the unitframe."] = true;
L["Display the target of the cast on the castbar."] = true;
L["Display tick marks on the castbar for channelled spells. This will adjust automatically for spells like Drain Soul and add additional ticks based on haste."] = true;
L["Down"] = true;
L["Fade the unitframe when out of combat, not casting, no target exists."] = true;
L["Fill"] = true;
L["Filled"] = true;
L["Filter Type"] = true;
L["Focus Frame"] = true;
L["FocusTarget Frame"] = true;
L['Force the frames to show, they will act as if they are the player frame.'] = true;
L["Format"] = true;
L["Frame"] = true;
L["Frequent Updates"] = true;
L['Friendlies: Show Buffs'] = true;
L['Friendlies: Show Debuffs'] = true;
L["Ghost"] = true;
L["Good"] = true;
L["Group By"] = true;
L["Group Point"] = true;
L["Heal Prediction"] = true;
L["Health Backdrop"] = true;
L["Health By Value"] = true;
L["Health Text"] = true;
L["Health"] = true;
L["Height"] = true;
L['Hold shift + right click to blacklist this aura.'] = true;
L["Horizontal"] = true; --Also used in bags module
L["How far away the portrait is from the camera."] = true;
L["Icon"] = true;
L['If not set to 0 then override the size of the aura icon to this.'] = true;
L['If set then if the aura is found on the blacklist filter it will not display. Note: You can change between only doing this on friendly or enemy units.'] = true;
L['If set then if the aura is found on the whitelist filter it will display. Note: You can change between only doing this on friendly or enemy units.'] = true;
L['If set, only auras belonging to yourself in addition to any aura that passes the set filter may be shown. Note: You can change between only doing this on friendly or enemy units.'] = true;
L["Interrupt Color"] = true;
L["Latency"] = true;
L["Length"] = true;
L["Long (Include Level)"] = true;
L["Long"] = true;
L["Low Mana Threshold"] = true;
L["Main statusbar texture."] = true;
L["Match Frame Width"] = true;
L["Max Columns"] = true;
L["Medium"] = true;
L["MT, MA First"] = true;
L["Name"] = true; --Also used in Buffs and Debuffs
L["Neutral"] = true;
L['No Consolidated'] = true;
L['No Duration'] = true;
L["None"] = true; --Also used in chat
L["Not valid spell id"] = true;
L["Num Rows"] = true;
L["Offline"] = true;
L["Offset of the powerbar to the healthbar, set to 0 to disable."] = true;
L["Offset"] = true;
L["OOR Alpha"] = true;
L["Orientation"] = true;
L["Overlay the healthbar"] = true;
L["Overlay"] = true;
L["Override any custom visibility setting in certain situations, EX: Only show groups 1 and 2 inside a 10 man instance."] = true;
L["Party Frames"] = true;
L["Party Pets"] = true;
L["Party Targets"] = true;
L["Per Row"] = true;
L["Percent"] = true;
L["Personal Auras"] = true;
L["PetTarget Frame"] = true;
L["Player Frame"] = true;
L["Portrait"] = true;
L["Position"] = true;
L["Power text will be hidden on NPC targets, in addition the name text will be repositioned to the power texts anchor point."] = true;
L["Power"] = true;
L["Powers"] = true;
L["Priority"] = true;
L['Raid-10 Frames'] = true;
L['Raid-25 Frames'] = true;
L['Raid-40 Frames'] = true;
L["RaidDebuff Indicator"] = true;
L["Rapidly update the health, uses more memory and cpu. Only recommended for healing."] = true;
L["Reactions"] = true;
L["Remaining"] = true;
L["Remove a spell from the filter."] = true;
L["Remove Spell"] = true;
L["Remove SpellID"] = true;
L["Rest Icon"] = true;
L["Restore Defaults"] = true; --Also used in General and ActionBars sections
L['RL / ML Icons'] = true;
L["Role Icon"] = true;
L["Select a filter to use."] = true; --Also used in NamePlates
L["Select a unit to copy settings from."] = true;
L["Select Filter"] = true;
L["Select Spell"] = true;
L["Set the filter type, blacklisted filters hide any aura on the like and show all else, whitelisted filters show any aura on the filter and hide all else."] = true;
L["Set the font size for unitframes."] = true;
L["Set the order that the group will sort."] = true;
L["Set the priority order of the spell, please note that prioritys are only used for the raid debuff module, not the standard buff/debuff module. If you want to disable set to zero."] = true;
L["Short"] = true;
L["Show a incomming heal prediction bar on the unitframe. Also display a slightly different colored bar for incoming overheals."] = true;
L['Show Auras'] = true;
L["Show Missing"] = true;
L["Show Party"] = true;
L["Show Raid"] = true;
L["Show Solo"] = true;
L["Size of the indicator icon."] = true;
L['Size Override'] = true;
L["Size"] = true;
L['Smart Auras'] = true;
L["Smart Raid Filter"] = true;
L["Smooth Bars"] = true;
L["Spaced"] = true;
L["Spark"] = true;
L["Spell not found in list."] = true;
L["StatusBar Texture"] = true;
L["Tank Frames"] = true;
L["Tapped"] = true;
L["Target Frame"] = true;
L["TargetTarget Frame"] = true;
L["Text Format"] = true;
L["Text Toggle On NPC"] = true;
L["Text"] = true;
L["The alpha to set units that are out of range to."] = true;
L["The amount of space (in pixels) between the columns."] = true;
L["The anchor point for each new column. A value of LEFT will cause the columns to grow to the right."] = true;
L["The following macro must be true in order for the group to be shown, in addition to any filter that may already be set."] = true;
L["The font that the unitframes will use."] = true;
L["The maximum number of columns that the header will create."] = true;
L["The maximum number of units that will be displayed in a single column."] = true;
L['The object you want to attach to.'] = true;
L['The point of which you are anchoring to in relation to the attach to object.'] = true;
L['The spell "%s" has been added to the Blacklist unitframe aura filter.'] = true;
L["Ticks"] = true;
L["Toggles health text display"] = true;
L["UnitFrames"] = true;
L["Units Per Column"] = true;
L["Up"] = true;
L['Use Blacklist'] = true;
L["Use Filter"] = true;
L["Use the custom health backdrop color instead of a multiple of the main health color."] = true;
L['Use Whitelist'] = true;
L["Value must be a number"] = true;
L["Vertical"] = true; --Also used in bags section
L["Visibility"] = true;
L["What each frame should attach itself to, example setting it to TOP every unit will attach its top to the last point bottom."] = true;
L["What point to anchor to the frame you set to attach to."] = true;
L["What to attach the buff anchor frame to."] = true;
L['When set the Buffs and Debuffs will toggle being displayed depending on if the unit is friendly or an enemy. This will not effect the aurabars module.'] = true;
L["When true, the group header is shown when the player is in a party."] = true;
L["When true, the group header is shown when the player is in a raid."] = true;
L["When true, the header includes the player when not in a raid."] = true;
L["When true, the header is shown when the player is not in any group."] = true;
L["When you mana falls below this point, text will flash on the player frame."] = true;
L["Whitelist"] = true;
L["Width"] = true; --Also used in NamePlates module
L["xOffset"] = true;
L["yOffset"] = true; --Another variation in bags section Y Offset
L["You can't remove a pre-existing filter."] = true;
L["You cannot copy settings from the same unit."] = true;
L["You cannot set the Group Point and Column Point so they are opposite of each other."] = true;
L["You may not remove a spell from a default filter that is not customly added. Setting spell to false instead."] = true;